/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Icons from './'
const all = [
  { name: 'AmericanexpressLightLarge', component: Icons.AmericanexpressLightLarge },
  { name: 'BitcoinLightLarge', component: Icons.BitcoinLightLarge },
  { name: 'CirrusLightLarge', component: Icons.CirrusLightLarge },
  { name: 'DinnerclubLightLarge', component: Icons.DinnerclubLightLarge },
  { name: 'DiscoverLightLarge', component: Icons.DiscoverLightLarge },
  { name: 'JcbLightLarge', component: Icons.JcbLightLarge },
  { name: 'MaestroLightLarge', component: Icons.MaestroLightLarge },
  { name: 'MastercardLightLarge', component: Icons.MastercardLightLarge },
  { name: 'PaypalLightLarge', component: Icons.PaypalLightLarge },
  { name: 'VisaLightLarge', component: Icons.VisaLightLarge },
]
export default all
