/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBitcoinLightLarge = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 48 32"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <rect width={48} height={32} rx={4} fill="#DFE3E8" />
    <path
      d="M34.29 18.57c-1.42 5.677-7.171 9.13-12.849 7.713-5.678-1.417-9.133-7.166-7.72-12.845C15.132 7.76 20.88 4.301 26.56 5.71a10.6 10.6 0 017.73 12.86z"
      fill="#F7941F"
    />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M28.68 14.49c.21-1.41-.87-2.17-2.34-2.68l.48-1.91-1.16-.29-.47 1.86-.93-.22.47-1.87-1.17-.29-.47 1.91-.75-.17-1.61-.4-.31 1.24s.86.2.85.21a.62.62 0 01.54.68l-.54 2.18h-.01l-.76 3a.42.42 0 01-.53.27l-.85-.21-.57 1.33 1.51.38.83.22-.48 1.93 1.16.29.48-1.91.92.24-.47 1.9 1.16.29.49-1.93c2 .38 3.47.22 4.1-1.57a2 2 0 00-1.07-2.82 1.88 1.88 0 001.49-1.71l.01.05zM26 18.22c-.33 1.317-2.398.777-3.346.53a15.486 15.486 0 00-.234-.06l.63-2.57.294.069c.987.223 2.988.677 2.656 2.031zm-2.454-3.221c.779.208 2.511.672 2.814-.529h.02c.303-1.22-1.345-1.6-2.134-1.78-.096-.023-.18-.042-.246-.06l-.64 2.32.186.049z"
      fill="#fff"
    />
  </svg>
))
export default SvgBitcoinLightLarge
