/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgJcbLightLarge = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 48 32"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <rect width={48} height={32} rx={4} fill="#DFE3E8" />
    <path fill="#fff" d="M8.03 10.41h9.85v13.54H8.03zM19.09 10.41h9.87v11.9h-9.87zM30.14 10.13h9.85v13.02h-9.85z" />
    <path d="M32.1 18.57h2.59a1 1 0 00.81-1 1.07 1.07 0 00-.81-1 1.225 1.225 0 00-.28 0H32.1v2z" fill="#40A648" />
    <path
      d="M34.14 4a4 4 0 00-4 4v4.15h5.65c.133-.016.267-.016.4 0 1.27.06 2.22.72 2.22 1.86a1.88 1.88 0 01-1.83 1.83c1.3.09 2.29.81 2.29 1.94s-1.1 2-2.55 2h-6.2V28H36a4 4 0 004-4V4h-5.86z"
      fill="#40A648"
    />
    <path d="M35.22 14.31a.94.94 0 00-.81-1H32.1v1.93h2.09a.93.93 0 001.03-.94v.01z" fill="#40A648" />
    <path
      d="M12 4a4 4 0 00-4 4v9.87a7.909 7.909 0 003.45.9 1.92 1.92 0 002.14-2v-4.64H17v4.64c0 1.8-1.12 3.27-4.92 3.27a16.998 16.998 0 01-4.08-.5V28h5.87a4 4 0 004-4V4H12z"
      fill="#0D67B0"
    />
    <path
      d="M23.09 4a4 4 0 00-4 4v5.23c1-.86 2.77-1.41 5.6-1.27 1.06.063 2.11.224 3.14.48v1.69a7.59 7.59 0 00-3-.88c-2.15-.15-3.45.9-3.45 2.75s1.3 2.92 3.45 2.75a8.098 8.098 0 003-.88v1.69c-1.03.258-2.08.419-3.14.48-2.83.14-4.59-.41-5.6-1.27V28H25a4 4 0 004-4V4h-5.91z"
      fill="#BE2034"
    />
  </svg>
))
export default SvgJcbLightLarge
