/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMaestroLightLarge = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 48 32"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <rect width={48} height={32} rx={4} fill="#DFE3E8" />
    <path fill="#fff" d="M4.65 3.2h38.71v25.6H4.65z" opacity={0.01} />
    <path fill="#7272B5" d="M18.9 7.66h10.21v16.68H18.9z" />
    <path d="M20 16a10.58 10.58 0 014-8.34 10.61 10.61 0 100 16.68A10.58 10.58 0 0120 16z" fill="#ED1C24" />
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M40.14 22.23v.34h-.06v-.34h-.14v-.07h.35v.07h-.15zm.68-.07v.41h-.07v-.31l-.11.27h-.08l-.12-.27v.31h-.07v-.41h.1l.13.29.12-.29h.1z"
      fill="#00A1DE"
    />
    <path
      d="M41.16 16A10.61 10.61 0 0124 24.34c4.6-3.622 5.397-10.286 1.78-14.89A10.399 10.399 0 0024 7.66 10.61 10.61 0 0141.16 16z"
      fill="#00A1DE"
    />
  </svg>
))
export default SvgMaestroLightLarge
