/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgAirplane = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M21.435 2.565a1.93 1.93 0 00-2.756.028l-4.097 4.27-9.999-3.31-2.099 2.1 8.334 5.131-4.217 4.395-2.704-.444L2 16.632l3.976 1.392L7.368 22l1.897-1.897-.444-2.704 4.395-4.217 5.131 8.334 2.1-2.1-3.31-9.998 4.27-4.097a1.93 1.93 0 00.028-2.756z"
      stroke="none"
      strokeWidth={1}
      fillRule="evenodd"
    />
  </svg>
))
export default SvgAirplane
