/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBus = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="1em" height="1em" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8.12 21.18a1.1 1.1 0 110-2.2 1.1 1.1 0 010 2.2m0-3.21a2.11 2.11 0 110 4.22 2.11 2.11 0 010-4.22zm14.38 0a2.11 2.11 0 110 4.22 2.11 2.11 0 010-4.22zm0 1a1.1 1.1 0 100 2.2 1.1 1.1 0 000-2.2zM28.46 9c1.87 0 1.5 1.41 1.52 1.96h-6.74s-.51.02-.51.42c0 .39.03 1.66.1 2.08.06.43.27.87 1.07 1.06.32.08 5.8 1.76 5.8 1.76.16.03.28.18.28.35v2.94c0 .2-.17.37-.37.37l-4.43-.05a2.7 2.7 0 00-5.37.03H11l-.22-.16a2.7 2.7 0 10-5.35.63l-.22.18L2 20.24c.1-.16.01-10.02 0-11.14V9zm-7.37 1.99H3.66c-.09 0-.15.04-.15.1v3.35c0 .06.06.1.15.1h17.43c.08 0 .15-.04.15-.1V11.1c0-.06-.07-.1-.15-.1z"
    />
  </svg>
))
export default SvgBus
