/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBusDimensions = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 84 56" ref={svgRef} {...props}>
    <g fill="none" fillRule="evenodd">
      <g strokeLinecap="square">
        <path stroke="#4D4E4C" d="M1 23V13h6" />
        <path stroke="#D8DAD9" d="M1 55h63v-6" />
      </g>
      <path
        fill="currentColor"
        d="M14.878 51.436a2.318 2.318 0 110-4.637 2.318 2.318 0 010 4.637m-4.453-2.318a4.453 4.453 0 118.906 0 4.453 4.453 0 01-8.906 0zm34.788-4.453a4.453 4.453 0 110 8.905 4.453 4.453 0 010-8.905zm0 6.77a2.318 2.318 0 100-4.635 2.318 2.318 0 000 4.636zm2.953-14.04c.666.158 12.216 3.701 12.216 3.701a.775.775 0 01.606.754v6.206a.774.774 0 01-.771.772l-9.345-.116a5.68 5.68 0 00-11.337.077h-18.56l-.46-.34a5.68 5.68 0 10-11.282 1.323l-.472.374-6.792-.69c.21-.351 0-23.706 0-23.706h55.806c3.954 0 3.186 2.982 3.213 4.138H46.78s-1.084.042-1.084.873c0 .83.073 3.512.206 4.404.134.892.568 1.83 2.264 2.23zm-5.622-.162V30.16c0-.12-.142-.219-.316-.219H5.464c-.174 0-.316.099-.316.219v7.073c0 .12.142.218.316.218h36.764c.174 0 .316-.098.316-.218z"
      />
    </g>
  </svg>
))
export default SvgBusDimensions
