/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCar2 = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="1em" height="1em" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8.22 19.48a2.38 2.38 0 110 4.77 2.38 2.38 0 010-4.77zm15.62 0a2.43 2.43 0 012.48 2.39 2.38 2.38 0 11-2.48-2.39zm.06 1.15a1.24 1.24 0 00-.06 2.48c.7.01 1.27-.54 1.29-1.24 0-.68-.55-1.24-1.23-1.24zm-15.66 0a1.24 1.24 0 00-.02 2.48c.69 0 1.25-.55 1.26-1.24 0-.69-.55-1.24-1.24-1.24zM17.15 8c.25 0 .45.18.47.43v1.44h1.36c.2 0 .4.07.55.2l.09.08.36.44 3.35 4.09h2.99a2.8 2.8 0 012.8 2.8v2.05l.11.02c.45.08.78.47.77.93v.07c0 .52-.42.94-.94.94H27.2a3.4 3.4 0 00-6.77 0h-8.84a3.4 3.4 0 00-6.77 0h-.87a.94.94 0 01-.94-.94v-.07c0-.52.42-.94.94-.94h-1a.94.94 0 01-.94-.93v-4.9c0-.52.42-.94.94-.94H3c.52 0 .94.42.94.94v-1.97c0-1 .8-1.83 1.8-1.87h1.12V8.43c0-.09.04-.17.09-.25L7 8.12c.09-.08.2-.12.32-.12zm-4.5 2.8H5.82a.94.94 0 00-.93.94v2.39c0 .47.3.54.76.55h6.98V10.8zm6.45 0h-5.5v3.88h9.36L19.1 10.8zm-2.42-1.86H7.8v.93h8.88v-.93z"
    />
  </svg>
))
export default SvgCar2
