/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCar4 = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="1em" height="1em" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M22.97 16.6a2.45 2.45 0 10-.01 4.9 2.45 2.45 0 000-4.9zm-14.2 0a2.45 2.45 0 110 4.9 2.45 2.45 0 010-4.9zm4.76-6.6c5.7 0 5.1 3.78 7.67 3.76 2.57-.02 7.22 2.13 8.3 3 .92.73.3.99.27 3.27l-3.47.64-.01-1.63a3.33 3.33 0 00-1.65-2.99 3.4 3.4 0 00-3.44 0 3.33 3.33 0 00-1.65 3v.36h-.01v1.22h-7.3v-1.22h-.02v-.37c0-1.84-1.51-3.34-3.37-3.34a3.36 3.36 0 00-3.37 3.34c0 .12-.02 1.47 0 1.59h-1.3c-2.95-.95-3.13-3.49.86-7.8C7.54 10.77 7.82 10 13.53 10zm9.44 7.75a1.28 1.28 0 110 2.57 1.28 1.28 0 010-2.57zm-14.2 0a1.28 1.28 0 100 2.57 1.28 1.28 0 000-2.57zm3.43-7.09l-1.11.02c0 .22-.1 2.73.17 2.73v-.02s5.86 0 7.69.02c-1.79-1.57-2.15-2.66-6.75-2.75zm-2.07.04c-2.46.25-3.83 2.7-3.05 2.7h3.05l.08-2.67c0-.03-.02-.03-.08-.03z"
    />
  </svg>
))
export default SvgCar4
