/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCaravanDimensions = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 84 56" ref={svgRef} {...props}>
    <g fill="none" fillRule="evenodd">
      <g strokeLinecap="square">
        <path stroke="#4D4E4C" d="M1 22V12h6" />
        <path stroke="#D8DAD9" d="M1 55h63v-6" />
      </g>
      <path
        fill="currentColor"
        d="M61.366 46.328h-4.272c.081-.36.032-.737-.138-1.064l-3.938-8.702c-5-11.32-6.89-19.687-17.718-19.687H7.875a5.907 5.907 0 00-5.906 5.828v23.625a3.78 3.78 0 003.8 3.8h14.51v-.769a6.99 6.99 0 0113.958 0v.768h27.129v-3.8zM25.928 31.404a1.969 1.969 0 01-1.968 1.97H8.21a1.969 1.969 0 01-1.969-1.97V23.53c0-1.087.881-1.968 1.969-1.968h15.75c1.087 0 1.968.881 1.968 1.968v7.875zm15.435 0a1.969 1.969 0 01-1.968 1.97H31.5a1.969 1.969 0 01-1.969-1.97V23.53c0-1.087.882-1.968 1.97-1.968h7.874c1.087 0 1.969.881 1.969 1.968l.02 7.875zM27.17 44.36a4.902 4.902 0 014.941 4.922 4.922 4.922 0 11-4.941-4.922zm0 7.481a2.56 2.56 0 10.04-5.119 2.56 2.56 0 00-.04 5.119z"
      />
    </g>
  </svg>
))
export default SvgCaravanDimensions
