/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCaravan = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="1em" height="1em" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M30 20.88h-2.01a.73.73 0 00-.07-.5l-1.86-4.1C23.71 10.94 22.82 7 17.71 7H4.78A2.78 2.78 0 002 9.75v11.13a1.78 1.78 0 001.8 1.8h6.83v-.37a3.3 3.3 0 016.58 0v.37H30v-1.8zm-16.7-7.03c0 .51-.42.93-.93.93H4.94a.93.93 0 01-.93-.93v-3.71c0-.52.42-.93.93-.93h7.43c.5 0 .92.41.92.93v3.7zm.58 6.1a2.31 2.31 0 012.33 2.33 2.32 2.32 0 11-2.33-2.32zm.01 1.12a1.2 1.2 0 100 2.41 1.2 1.2 0 000-2.41zm5.74-11.86c.52 0 .93.41.93.93l.01 3.7c0 .52-.41.94-.93.94h-3.72a.93.93 0 01-.93-.93v-3.71c0-.52.42-.93.93-.93h3.71z"
    />
  </svg>
))
export default SvgCaravan
