/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCarTrailer = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    xmlnsXlink="http://www.w3.org/1999/xlink"
    viewBox="0 0 32 32"
    width="1em"
    height="1em"
    ref={svgRef}
    {...props}
  >
    <defs>
      <path id="CarTrailer_svg__a" d="M0 0h32v32H0z" />
    </defs>
    <g fill="none" fillRule="evenodd">
      <mask id="CarTrailer_svg__b" fill="#fff">
        <use xlinkHref="#CarTrailer_svg__a" />
      </mask>
      <path
        fill="currentColor"
        d="M25.72 20.14c1.15 0 2.1.9 2.17 2.02l.01.16v.16a2.18 2.18 0 11-2.18-2.34zm-22.42 0c1.16 0 2.1.9 2.18 2.02v.32A2.18 2.18 0 012 24.07v-3.5c.37-.27.82-.43 1.3-.43zm22.42 1.04a1.14 1.14 0 100 2.28 1.14 1.14 0 000-2.28zm-22.42 0a1.14 1.14 0 00-.12 2.27h.12c.63 0 1.13-.5 1.14-1.13 0-.63-.5-1.14-1.14-1.14zM6.72 8c4.69 0 5.58 3.55 7.7 8.4l.12.3 1.74 3.84c.06.11.09.24.08.37l-.02.1h1.59c0 .36.06.73.19 1.08.06.15.13.3.22.43l.1.13-12.19.04v-.34A3.09 3.09 0 002 19.65V15.2c.3-.1.53-.38.57-.7l.01-.12V10.9c0-.38-.24-.7-.58-.82V8h4.72zm22.73 4.98H30V14c-.35.02-.69.04-1.02.04 0 .13.19 2.4.26 2.74.06.33-.03.48.67.5H30v5.33h-1.3v-.3a2.98 2.98 0 00-5.94-.18l-.02.17v.32h-2.41c-2.9 0-1.06-4.61.1-5.66 2.8-2.4 5.65-3.98 9.02-3.98zm-1.31 1.1h-.05c-3.12.32-4.78 3.06-3.93 3.2h4.04v-3.15c0-.02-.01-.03-.03-.04h-.03zM8.53 10.04H5.05c-.44 0-.8.34-.86.76v3.59c0 .45.32.81.75.86l.11.01h3.48c.44 0 .8-.33.86-.76v-3.6a.87.87 0 00-.86-.87z"
        mask="url(#CarTrailer_svg__b)"
      />
    </g>
  </svg>
))
export default SvgCarTrailer
