/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgFernettiLights = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12 2c1.306 0 2.418.835 2.83 2H19v16h-4v2H9v-2H5V4h4.17A3.001 3.001 0 0112 2zm0 13a2 2 0 100 4 2 2 0 000-4zm0-5a2 2 0 100 4 2 2 0 000-4zm0-5a2 2 0 100 4 2 2 0 000-4z"
      stroke="none"
      strokeWidth={1}
      fillRule="evenodd"
    />
  </svg>
))
export default SvgFernettiLights
