/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMinibus = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="1em" height="1em" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8.31 21.6a1.14 1.14 0 110-2.28 1.14 1.14 0 010 2.28m0-3.32a2.18 2.18 0 110 4.36 2.18 2.18 0 010-4.36zm16.03 0a2.18 2.18 0 110 4.36 2.18 2.18 0 010-4.36zm0 1.04a1.14 1.14 0 100 2.28 1.14 1.14 0 000-2.28zM19.51 9c1.94 0 4.94 1.6 5.7 2.03h-4s-.53.02-.53.43c0 .4.04.76.1 1.2.07.44.28.9 1.11 1.1l7.81 1.8c.17.05.3.2.3.38v4c0 .2-.17.38-.38.38l-2.48-.06a2.79 2.79 0 00-5.56.04H11.32l-.22-.17a2.79 2.79 0 10-5.54.65l-.23.19L2 20.63c.1-.17.01-10.4 0-11.53V9zm-1.25 2.06H4.46a.1.1 0 00-.12.1v3.47c0 .06.05.1.11.1h13.8a.1.1 0 00.11-.1v-3.47a.1.1 0 00-.1-.1z"
    />
  </svg>
))
export default SvgMinibus
