/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMinibusDimensions = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 84 56" ref={svgRef} {...props}>
    <g fill="none" fillRule="evenodd">
      <g strokeLinecap="square">
        <path stroke="#4D4E4C" d="M1 23V13h6" />
        <path stroke="#D8DAD9" d="M1 55h63v-6" />
      </g>
      <path
        fill="currentColor"
        d="M15.284 52.323a2.398 2.398 0 110-4.796 2.398 2.398 0 010 4.796m0-7.005a4.607 4.607 0 110 9.214 4.607 4.607 0 010-9.214zm33.812 0a4.607 4.607 0 110 9.214 4.607 4.607 0 010-9.214zm0 7.005a2.398 2.398 0 100-4.796 2.398 2.398 0 000 4.796zm11.308-12.72c.358.08.627.4.627.78v8.444a.8.8 0 01-.798.798l-5.24-.12a5.876 5.876 0 00-11.73.08h-21.63l-.477-.352a5.877 5.877 0 10-11.672 1.369l-.488.387-7.027-.714c.217-.363 0-24.525 0-24.525H38.9c4.09 0 10.415 3.382 12.024 4.281h-8.431s-1.122.043-1.122.903.076 1.61.214 2.533c.139.923.588 1.893 2.341 2.308.69.163 16.477 3.829 16.477 3.829zM36.488 37.63v-7.317a.227.227 0 00-.226-.226H7.14a.227.227 0 00-.226.226v7.317c0 .125.101.226.226.226h29.123a.227.227 0 00.226-.226z"
      />
    </g>
  </svg>
))
export default SvgMinibusDimensions
