/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMotorhomeDimensions = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 84 56" ref={svgRef} {...props}>
    <g fill="none" fillRule="evenodd">
      <g strokeLinecap="square">
        <path stroke="#4D4E4C" d="M1 23V13h6" />
        <path stroke="#D8DAD9" d="M1 55h63v-6" />
      </g>
      <path
        fill="currentColor"
        d="M15.284 51.757a2.398 2.398 0 110-4.797 2.398 2.398 0 010 4.797m0-7.005a4.607 4.607 0 110 9.213 4.607 4.607 0 010-9.213zm33.812 0a4.607 4.607 0 110 9.213 4.607 4.607 0 010-9.213zm0 7.005a2.398 2.398 0 100-4.797 2.398 2.398 0 000 4.797zm11.308-12.72c.358.079.627.4.627.78v8.443a.8.8 0 01-.798.798l-5.24-.119a5.876 5.876 0 00-11.73.08l-22.136.012c0-2.914-2.791-5.563-5.807-5.563a5.877 5.877 0 00-5.836 6.567l-7.515-.327V23.781h50.06c.643 0 1.205.343 1.514.856l.206.383 1.137 1.855a1.766 1.766 0 01-1.532 2.645h-11.2c-.33.085-.782.302-.782.848 0 .86.076 1.61.214 2.533.139.923.588 1.892 2.341 2.307.69.164 16.477 3.83 16.477 3.83zm-23.916 7.257V29.96a.443.443 0 00-.441-.441H29.16a.443.443 0 00-.441.441v16.333c0 .243.199.441.441.441h6.887a.443.443 0 00.441-.441zm-12.007-9.231v-7.317a.227.227 0 00-.226-.226H7.14a.227.227 0 00-.226.226v7.317c0 .124.101.226.226.226h17.116a.227.227 0 00.226-.226z"
      />
    </g>
  </svg>
))
export default SvgMotorhomeDimensions
