/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMotorHome = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="1em" height="1em" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M8.31 22.26a1.14 1.14 0 110-2.27 1.14 1.14 0 010 2.27m0-3.32a2.18 2.18 0 110 4.37 2.18 2.18 0 010-4.37zm16.03 0a2.18 2.18 0 110 4.37 2.18 2.18 0 010-4.37zm0 1.05a1.14 1.14 0 100 2.27 1.14 1.14 0 000-2.27zM25.74 9c.3 0 .56.16.71.4l.1.19.54.88c.07.12.1.26.1.41 0 .47-.37.84-.83.84h-5.3c-.17.04-.38.14-.38.4 0 .41.04.77.1 1.2.07.44.28.9 1.11 1.1l7.81 1.81c.17.04.3.2.3.37v4c0 .21-.17.38-.38.38l-2.48-.05a2.79 2.79 0 00-5.56.03l-10.5.01c0-1.38-1.32-2.64-2.75-2.64a2.79 2.79 0 00-2.77 3.12L2 21.29V9zm-7.58 2.72h-3.27c-.11 0-.2.1-.2.21v7.74c0 .12.09.21.2.21h3.27c.11 0 .2-.1.2-.2v-7.75c0-.12-.09-.21-.2-.21zm-5.6 0h-8.1a.1.1 0 00-.12.1v3.48c0 .06.05.1.11.1h8.12a.1.1 0 00.1-.1v-3.47a.1.1 0 00-.1-.11z"
    />
  </svg>
))
export default SvgMotorHome
