/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMotorcycleSidecar = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="1em" height="1em" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      fillRule="evenodd"
      d="M10.67 18.33a2.67 2.67 0 110 5.34 2.67 2.67 0 010-5.34zm.08 1.42c-.74 0-1.33.6-1.33 1.33 0 .74.55 1.34 1.29 1.34.73 0 1.37-.6 1.37-1.34 0-.73-.6-1.33-1.33-1.33zM20.37 9c.05 0 .09.03.1.07l.02.03c.19.39 1.94 4.05 2.91 6.03a3.62 3.62 0 11-1.02.47l.18-.1-.86-1.82-3.57 6.5a.12.12 0 01-.06.05l-.04.01h-.75a4.22 4.22 0 001.53-3.12c0-1.8-1.34-3.39-3.37-4.3l1.54-1.53a.11.11 0 01.05-.03h3.51l-.69-1.45H17.8a.12.12 0 01-.1-.08l-.01-.04v-.58c0-.05.03-.09.08-.1L17.8 9h2.58zm-5.97 4c2.22.8 3.73 2.36 3.73 4.15 0 1.8-1.51 3.36-3.74 4.16v-.07a3.76 3.76 0 00-7.5-.29C5.14 20.1 4 18.71 4 17.15c0-1.12.6-2.16 1.58-2.97 1 .87 2.38 1.4 3.91 1.4 2.1 0 3.93-1 4.85-2.5l.06-.08zm9.98 3.74a1.89 1.89 0 100 3.77 1.89 1.89 0 000-3.77zm-13.22-4.62h.03l.03.02 1.65 1.05.03.02h.84c-2.17 2.4-5.12 2.65-8.25.42h-.02v-1.39c0-.05.04-.1.08-.1l.04-.02h5.57z"
    />
  </svg>
))
export default SvgMotorcycleSidecar
