/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgPrivateVanDimensions = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 84 56" ref={svgRef} {...props}>
    <g fill="none" fillRule="evenodd">
      <g strokeLinecap="square">
        <path stroke="#4D4E4C" d="M1 23V13h6" />
        <path stroke="#D8DAD9" d="M1 55h63v-6" />
      </g>
      <path
        fill="currentColor"
        d="M14.921 52.297a2.427 2.427 0 110-4.854 2.427 2.427 0 010 4.854m0-7.091a4.663 4.663 0 110 9.326 4.663 4.663 0 010-9.326zm34.195 0a4.664 4.664 0 11-.002 9.327 4.664 4.664 0 01.002-9.327zm0 7.09a2.427 2.427 0 100-4.853 2.427 2.427 0 000 4.854zm11.288-12.692a.8.8 0 01.627.779v8.444a.8.8 0 01-.798.798l-5.24-.118a5.875 5.875 0 00-11.73.078h-21.63l-.476-.352a5.877 5.877 0 10-11.673 1.369l-.488.386-7.027-.714c.217-.362 0-24.524 0-24.524H38.9c4.09 0 10.416 3.382 12.024 4.282h-8.431s-1.121.042-1.121.902.075 1.611.213 2.534c.14.923.588 1.892 2.342 2.307.69.163 16.476 3.829 16.476 3.829z"
      />
    </g>
  </svg>
))
export default SvgPrivateVanDimensions
