/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgTrailerDimensions = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 84 56" ref={svgRef} {...props}>
    <g fill="none" fillRule="evenodd">
      <g strokeLinecap="square">
        <path stroke="#4D4E4C" d="M1 23V13h6" />
        <path stroke="#D8DAD9" d="M1 55h63v-6" />
      </g>
      <path
        fill="currentColor"
        d="M57.428 46.328v3.8H30.3v-.769a6.99 6.99 0 00-13.958 0v.768H6.32a3.78 3.78 0 01-3.8-3.8v-7.574c9.773-.14 34.28-.14 44.73-.14l-.139 6.651c.17.327.22.704.138 1.063h10.178zm-34.197-1.97a4.902 4.902 0 014.942 4.923 4.922 4.922 0 11-4.942-4.922zm0 7.482a2.56 2.56 0 10.04-5.119 2.56 2.56 0 00-.04 5.119zM7.906 28.687h33.407a2 2 0 012 2v5.875H5.906v-5.874a2 2 0 012-2z"
      />
    </g>
  </svg>
))
export default SvgTrailerDimensions
