/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBulkLiquid = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M25.39 8H6.93a6.172 6.172 0 00-6.154 6.154 6.172 6.172 0 006.154 6.154V24h1.23v-3.692h16V24h1.232v-3.692a6.172 6.172 0 006.154-6.154A6.172 6.172 0 0025.39 8zm-9.23 9.846a2.485 2.485 0 01-2.462-2.506c0-1.385 2.462-4.571 2.462-4.571s2.461 3.186 2.461 4.57a2.485 2.485 0 01-2.461 2.507z"
    />
  </svg>
))
export default SvgBulkLiquid
