/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCargoSelfDrive = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M14.036 22.062h11.473a3.493 3.493 0 00-.69 3.617H12.474v-1.417c0-2.244-1.773-4.062-4.016-4.062s-4.016 1.818-4.016 4.062v1.417H1.567c-.661 0-1.141-.755-1.141-1.416v-6.814s7.929-1.527 8.835-1.741 1.138-.716 1.21-1.193.11-.865.11-1.309c0-.445-.579-.467-.579-.467H.354C.327 11.4.41 8.04 3.249 7.64l9.559-1.248c.661 0 1.227.484 1.227 1.145v14.526zm-5.508 3.966a1.625 1.625 0 100-3.25 1.625 1.625 0 000 3.25zm0-4.747a3.122 3.122 0 110 6.245 3.122 3.122 0 010-6.245zm20.35 4.773a1.624 1.624 0 10.001-3.249 1.624 1.624 0 00-.001 3.249zm0-4.748a3.122 3.122 0 110 6.245 3.122 3.122 0 010-6.245z"
    />
  </svg>
))
export default SvgCargoSelfDrive
