/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgFactory = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 32 32"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <path
      d="M26.24 23.68v2.56h-5.12v-2.56h5.12zm0-5.12v2.56h-12.8v-2.56h12.8zm-7.68 5.12v2.56h-5.12v-2.56h5.12zm-7.68-5.12v2.56H5.76v-2.56h5.12zm0 5.12v2.56H5.76v-2.56h5.12zM28.8 28.8V10.88L22.4 16v-5.12L16 16v-5.12L9.6 16 8.32 3.2H4.48L3.2 16v12.8h25.6z"
      fill="currentColor"
    />
  </svg>
))
export default SvgFactory
