/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgHazardous = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M17.64 19.448c0 .154-.028.258-.088.32-.06.056-.164.088-.318.088h-2.468c-.152 0-.258-.032-.318-.088-.058-.062-.09-.166-.09-.32l-.33-9.734c0-.154.03-.26.09-.318.06-.06.164-.09.318-.09h3.128c.154 0 .258.03.32.09.058.058.088.164.088.318l-.332 9.734zm.332 6.278c0 .152-.03.258-.088.318-.062.06-.166.088-.32.088h-3.128c-.154 0-.258-.028-.318-.088s-.09-.166-.09-.318v-2.874c0-.154.03-.26.09-.32.06-.058.164-.088.318-.088h3.128c.154 0 .258.03.32.088.058.06.088.166.088.32v2.874zm13.898 2.736l-.282-.482L16.912 2.532A1.049 1.049 0 0015.998 2c-.4 0-.744.22-.922.544l-.174.302L.138 28.448a1.024 1.024 0 00-.138.514C0 29.534.47 30 1.048 30h29.906c.578 0 1.046-.466 1.046-1.038 0-.18-.046-.352-.13-.5z"
    />
  </svg>
))
export default SvgHazardous
