/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgReefer = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M32 16l-.8-1.4h-3.6l1.6-2.8-.8-1.4h-1.6l-2.6 4h-5.6l2.8-4.8h4.8l.8-1.4-.8-1.4H23l2-3.2-1-1.4h-1.8l-1.8 3.2-1.6-3h-1.6l-.8 1.4L18.8 8 16 13l-2.8-5 2.6-4.2-1-1.4h-1.6l-1.6 2.8L9.8 2H8l-.8 1.4L9 6.6H5.6l-.8 1.6.8 1.4h5l2.8 5H7.8l-2.4-4.2H3.8l-1 1.4 1.6 2.8H.8L0 16l.8 1.4h3.6l-1.6 2.8.8 1.4h1.6l2.6-4.2h5.6l-2.8 5h-5l-.8 1.4.8 1.6h3.2L7 28.6l.8 1.4h1.6l1.8-3.2 1.6 2.8h1.6l.8-1.4-2-4.4L16 19l2.8 4.8-2.6 4.2.8 1.4h1.6l1.6-2.8 1.8 3h2l.8-1.4L23 25h3.2l.8-1.6-.8-1.4h-4.8l-3-4.6h5.8l2.4 4.2h1.6l.8-1.4-1.6-2.8H31z"
    />
  </svg>
))
export default SvgReefer
