/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgShip1 = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="inherit"
      d="M0 16.455v-1.491h3.495v1.491H0zm13.053 0v-1.491h3.496v1.491h-3.496zm4.008 0v-1.491h3.496v1.491h-3.496zm4.008 0v-1.491h3.496v1.491h-3.496z"
    />
    <path
      fill="currentColor"
      d="M.977 20.152a5.765 5.765 0 01-.908-3.1l31.011-.03-1.776 3.099a7.808 7.808 0 00-.265-.005c-2.717 0-2.726 1.631-5.468 1.631s-5.46-1.628-8.19-1.628l-.011-.004c-2.73 0-5.448 1.63-8.19 1.63s-2.745-1.63-5.462-1.63c-.248 0-.496.013-.742.037zm9.666-8.3l1.852 4.631H4.16v-4.631h.693L5.459 10h1.625l1.032 1.852h2.527zm18.737 2.78l2.411 1-.494.851h-6.132l1.755-2.964h1.68l.606.955c0 .096.079.158.174.158z"
    />
  </svg>
))
export default SvgShip1
