/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgShip2 = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M.936 21.984A6.048 6.048 0 010 18.757h31.973l-1.831 3.195a8.286 8.286 0 00-.273-.005c-2.801 0-2.811 1.681-5.637 1.681s-5.629-1.678-8.444-1.678l-.011-.004c-2.814 0-5.618 1.681-8.444 1.681s-2.83-1.681-5.631-1.681c-.256 0-.512.014-.765.038zM8.61 11.91l.038 6.291H0V11.91h.768L1.393 10h1.675l1.064 1.91h4.477z"
    />
    <path
      fill="inherit"
      d="M13.299 18.171v-1.793h3.604v1.793h-3.604zm4.133 0v-1.793h3.604v1.793h-3.604zm-8.27 0v-1.793h3.604v1.793H9.162zm12.402 0v-1.793h3.604v1.793h-3.604zm4.142 0v-1.793h3.604v1.793h-3.604zm-12.407-2.24v-1.793h3.604v1.793h-3.604zm-4.137 0v-1.793h3.604v1.793H9.162z"
    />
  </svg>
))
export default SvgShip2
