/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgTrackingEmpty = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M29.714 8H32v15.771H0V8h2.286v13.485h27.428V8zm-8.457 2.032l-3.911 3.911 3.911 3.911-1.117 1.118-3.911-3.912-3.911 3.912-1.117-1.118 3.911-3.911-3.911-3.911 1.117-1.117 3.911 3.911 3.911-3.911 1.117 1.117z"
    />
  </svg>
))
export default SvgTrackingEmpty
