/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgTrackingLoadedOnVessel = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 33 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M1.47 20.132a5.717 5.717 0 01-.901-3.077l30.786-.041-1.762 3.077h-.263c-2.698 0-2.698 1.618-5.427 1.618s-5.427-1.615-8.138-1.615c-2.717 0-5.418 1.618-8.138 1.618s-2.726-1.618-5.421-1.618c-.244 0-.491.013-.736.038zM.5 14.984h3.471v1.48H.5v-1.48zm12.955 0h3.471v1.48h-3.471v-1.48zm7.956 0h3.471v1.48h-3.471v-1.48zm-10.348-3.09l1.84 4.598H4.628v-4.598h.689l.601-1.837H7.53l1.027 1.837h2.507zm18.598 2.761l2.394 1.002-.491.845h-6.085l1.74-2.942h1.668l.601.939c.001.044.02.086.052.115s.076.044.12.041zm-7.904-2.548l-2.487 2.522-2.541-2.516.729-.756 1.334 1.322v-2.164h1.04v2.05l1.187-1.206.738.748z"
    />
    <path fill="inherit" d="M17.433 14.984h3.471v1.48h-3.471v-1.48z" />
  </svg>
))
export default SvgTrackingLoadedOnVessel
