/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgTrackingShipCancelled = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path fill="inherit" d="M20.312 8l-9.15 15.848h1.084L21.397 8z" />
    <path
      fill="currentColor"
      d="M10.47 11.369l1.822 4.555H4.093v-4.555h.682l.596-1.822h1.598l1.016 1.822h2.486zm5.064 3.061l-.847 1.466H12.84V14.43h2.694zm2.369 1.466l.847-1.466h1.473v1.466h-2.319zm-.33.571l13.002-.012-1.747 3.048a7.574 7.574 0 00-.261-.005c-2.672 0-2.681 1.605-5.378 1.605-2.473 0-4.926-1.343-7.387-1.567l1.771-3.068zm-3.217.003l-2.002 3.468c-1.76.474-3.52 1.162-5.29 1.162-2.697 0-2.7-1.603-5.373-1.603-.244 0-.488.012-.73.036a5.668 5.668 0 01-.893-3.05l14.287-.014zM0 15.896v-1.467h3.439v1.467H0zm20.726 0V14.43h3.439v1.466h-3.439zm3.681-2.895h6.195v3h-6.195v-3z"
    />
  </svg>
))
export default SvgTrackingShipCancelled
