/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgTrackingFull = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path fill="inherit" d="M29.714 8v13.485H2.286V8H0v15.772h32V8z" />
    <path
      fill="currentColor"
      d="M20.589 10.491l-3.712 7.055a.954.954 0 01-1.454.292l-3.951-3.261a.955.955 0 111.217-1.475l3.044 2.512 3.163-6.013a.955.955 0 111.693.89zM3.886 19.886h24.229V8H3.886v11.886z"
    />
  </svg>
))
export default SvgTrackingFull
