/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgTrackingGateIn = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M10.51 18.493a1.676 1.676 0 110 3.352 1.676 1.676 0 010-3.352zm3.822 0a1.676 1.676 0 110 3.352 1.676 1.676 0 010-3.352zM3.878 13.029L6.4 15.516l-2.516 2.541-.756-.729 1.322-1.334H2.286v-1.04h2.05L3.13 13.767l.748-.738zM0 9.829h.914v11.886H0V9.829zm23.771 8.822h.914v3.2h-.914v-3.2zM10.51 21.032v.007a.87.87 0 00.87-.878.87.87 0 10-.871.871zm3.822 0v.007a.87.87 0 00.87-.878.87.87 0 10-.871.871z"
    />
    <path fill="inherit" d="M8.771 9.829H29.87a1 1 0 011 1v6.37a1 1 0 01-1 1H8.771a1 1 0 01-1-1v-6.37a1 1 0 011-1z" />
  </svg>
))
export default SvgTrackingGateIn
