/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgWarehouseHighValue = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M2.792 22.631H8.07v2.578H1.871l.921-2.578zm5.653 2.578v-2.578h7.137v2.578H8.445zm7.518 0v-2.578H23.1v2.578h-7.137zm7.513-2.578h5.299l.921 2.578h-6.22v-2.578zM8.445 22.25v-2.579h7.137v2.579H8.445zm7.518 0v-2.579H23.1v2.579h-7.137zm7.513-2.578h4.243l.921 2.579h-5.164v-2.579zm0-2.95h3.19l.921 2.579h-4.11v-2.579zM15.768 6L31.54 9.376v15.838h-1.404l-3.201-8.873H4.605l-3.2 8.873H0V9.376L15.768 6z"
    />
    <path
      fill="inherit"
      d="M17.346 10.827h-3.15v-.505a1.576 1.576 0 013.15 0v.505zm-1.26 2.118v.678a.315.315 0 11-.63 0v-.678a.628.628 0 01.315-1.173.63.63 0 01.315 1.173zm1.889-2.118v-.505c0-1.216-.989-2.205-2.205-2.205s-2.205.989-2.205 2.205v.505a.316.316 0 00-.315.315v3.15c0 .173.142.315.315.315h4.41a.316.316 0 00.315-.315v-3.15a.316.316 0 00-.315-.315z"
    />
  </svg>
))
export default SvgWarehouseHighValue
