/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgWarehouse = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="inherit"
      d="M1 25.487v-2.578h7.135v2.578H1zm7.515 0v-2.578h7.135v2.578H8.515zm7.515 0v-2.578h7.135v2.578H16.03zm7.516 0v-2.578h7.135v2.578h-7.135zM8.515 22.53v-2.578h7.135v2.578H8.515zm7.515 0v-2.578h7.135v2.578H16.03zm7.516 0v-2.578h7.135v2.578h-7.135zm0-2.952V17h7.135v2.578h-7.135z"
    />
    <path fill="currentColor" d="M16 6L0 9.424v16.07h1.424l3.25-13.512h22.651l3.251 13.512H32V9.424z" />
  </svg>
))
export default SvgWarehouse
