/* eslint-disable deprecation/deprecation */
/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Icons from './'
//** @deprecated *//
const all = [
  { name: 'Document', component: Icons.Document },
  { name: 'Download', component: Icons.Download },
  { name: 'ExternalLink', component: Icons.ExternalLink },
  { name: 'Invoice', component: Icons.Invoice },
  { name: 'LeftLink', component: Icons.LeftLink },
  { name: 'Link', component: Icons.Link },
  { name: 'Modal', component: Icons.Modal },
  { name: 'Pdf', component: Icons.Pdf },
  { name: 'RightLink', component: Icons.RightLink },
  { name: 'Unlink', component: Icons.Unlink },
  { name: 'Upload', component: Icons.Upload },
]
export default all
