/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgDownload = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M18.161 4.474v19.681l8.495-8.495 2.842 2.842L16 32 2.501 18.501l2.842-2.842 8.344 8.344V4.474H2.502V0h26.845v4.474H18.162z"
    />
  </svg>
))
export default SvgDownload
