/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgExternalLink = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M28.407 6.421L14.929 19.899l-2.828-2.828L25.579 3.593H14.934V0H32v17.067h-3.593V6.422zM24 28.4V32H0V8h12v3.6H3.6v16.8h16.8V20H24v8.4z"
    />
  </svg>
))
export default SvgExternalLink
