/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgLink = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M11.257 19.055v2.764H3.002V10.183h8.255v3.055h3.002v-3.2c0-.733-.3-1.436-.835-1.954s-1.26-.809-2.016-.809H2.853c-1.575 0-2.852 1.237-2.852 2.764v11.927c0 .733.3 1.436.835 1.954s1.26.809 2.016.809h8.555c.756 0 1.482-.291 2.016-.809s.835-1.221.835-1.954v-2.909h-3.002zm9.305-.002v2.764h8.255V10.181h-8.105v3.055H17.71v-3.2c0-1.526 1.277-2.764 2.852-2.764h8.555c1.575 0 2.852 1.237 2.852 2.764v11.927c.001.759-.32 1.485-.888 2.007s-1.332.796-2.114.756h-8.555c-.756 0-1.482-.291-2.016-.809s-.835-1.221-.835-1.954v-2.909h3.002z"
    />
    <path
      fill="currentColor"
      d="M24.014 17.455H7.654c-.829 0-1.501-.651-1.501-1.455s.672-1.455 1.501-1.455h16.36c.829 0 1.501.651 1.501 1.455s-.672 1.455-1.501 1.455z"
    />
  </svg>
))
export default SvgLink
