/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgModal = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" width="1em" height="1em" ref={svgRef} {...props}>
    <g fill="currentColor" fillRule="evenodd">
      <path d="M24 32H0V8h6v3.6l-2.402-.002V28.4H20.4V26H24v6z" />
      <path d="M8 24V0h24v3.6l-.002-.002L32 20.4V24H8zm20.4-3.6V3.598H11.598V20.4H28.4z" />
    </g>
  </svg>
))
export default SvgModal
