/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgUpload = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M13.839 27.526V7.845L5.344 16.34l-2.842-2.842L16 0l13.499 13.499-2.842 2.842-8.344-8.344v19.529h11.185V32H2.653v-4.474h11.185z"
    />
  </svg>
))
export default SvgUpload
