/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgAccountSignedOut = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="inherit"
      d="M22.667 18.537V15.18c0-2.225 1.791-4.028 4-4.028s4 1.803 4 4.028v3.357H32v10.07H21.333v-10.07h1.333zm1.867-.198h4.267V15.13c0-1.063-.955-1.925-2.133-1.925s-2.133.862-2.133 1.925v3.209z"
    />
    <path
      fill="currentColor"
      d="M19.394 27.743a25.492 25.492 0 01-6.788.861l-.215.002c-4.412 0-8.936-1.167-12.392-3.364l.087-.877a6.946 6.946 0 011.204-3.463 7.143 7.143 0 015.896-3.112h1.393l.374.003c.453 0 .793.086 1.02.262.227.174.465.485.718.934l1.939 3.291 1.889-3.291c.253-.449.491-.76.718-.934.227-.176.567-.262 1.02-.262l.374-.003h1.393a7.1 7.1 0 011.369.132v9.821zm-6.788-10.914c-3.749 0-6.788-3.007-6.788-6.717s3.038-6.718 6.788-6.718c3.748 0 6.788 3.007 6.788 6.718s-3.039 6.717-6.788 6.717z"
    />
  </svg>
))
export default SvgAccountSignedOut
