/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgBack = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M8.303 12.05h9.715a8.002 8.002 0 110 16.004H5.375V32h12.646C24.637 32 30 26.637 30 20.021S24.637 8.042 18.021 8.042H8.02l5.952-5.952L11.891.009 1.992 9.908l9.884 9.884 2.084-2.084-5.657-5.657z"
    />
  </svg>
))
export default SvgBack
