/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgBurgerMenu = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M1.846 23.692h28.308a1.846 1.846 0 010 3.692H1.846a1.846 1.846 0 010-3.692zm0-9.846h28.308a1.846 1.846 0 010 3.692H1.846a1.846 1.846 0 010-3.692zm0-9.846h28.308a1.846 1.846 0 010 3.692H1.846a1.846 1.846 0 010-3.692z"
    />
  </svg>
))
export default SvgBurgerMenu
