/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgCancelled = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M23.067 6.3A11.943 11.943 0 0016 4C9.373 4 4 9.373 4 16c0 2.618.838 5.04 2.261 7.013L23.066 6.301zm2.795 2.862L9.107 25.824A11.945 11.945 0 0016 28c6.627 0 12-5.373 12-12 0-2.541-.79-4.898-2.138-6.838zM16 0a15.997 15.997 0 0116 16c0 8.837-7.163 16-16 16S0 24.837 0 16 7.163 0 16 0z"
    />
  </svg>
))
export default SvgCancelled
