/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgClear = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      color="currentColor"
      d="M16 32C7.163 32 0 24.837 0 16S7.163 0 16 0s16 7.163 16 16-7.163 16-16 16zm4.978-22.4L16 14.578 11.023 9.6l-1.422 1.422L14.578 16l-4.977 4.978 1.422 1.422L16 17.422l4.978 4.978 1.422-1.422L17.422 16l4.978-4.978L20.978 9.6z"
    />
  </svg>
))
export default SvgClear
