/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgDelete = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M28.933 3.739h-8.367v-.78A2.955 2.955 0 0017.608.001h-3.504a2.958 2.958 0 00-2.958 2.958v.78H2.787a2.786 2.786 0 000 5.572h.898v19.902a2.606 2.606 0 002.599 2.599h19.044a2.606 2.606 0 002.599-2.599V9.311h1.007a2.786 2.786 0 000-5.572zm-15.961-.953c0-.549.443-.995.991-.999h3.778c.562.017 1.004.484.991 1.046v.944h-5.76v-.991zm13.221 26.381a.859.859 0 01-.859.859H6.368a.859.859 0 01-.859-.859V9.366h3.856v16.953a.976.976 0 101.944 0V9.367v-.055h3.645v17.007a.968.968 0 101.936 0V9.367v-.055h3.684v17.007a.968.968 0 101.936 0V9.367v-.055h3.778l-.094 19.856zM28.784 7.36H2.934a1 1 0 110-1.99h25.85a1 1 0 010 1.99z"
    />
  </svg>
))
export default SvgDelete
