/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgDisabled = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 26 26" ref={svgRef} {...props}>
    <path
      stroke="currentColor"
      d="M21.438 4.528L21.41 4.5l-8.42 8.44L4.57 4.5l-.028.028 8.42 8.44-8.463 8.485.028.028 8.463-8.484 8.463 8.484.028-.028-8.463-8.484 8.42-8.44z"
    />
  </svg>
))
export default SvgDisabled
