/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgDurationTime = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M15.629 30.629C7.55 30.629 1 24.08 1 16S7.549 1.371 15.629 1.371c8.079 0 14.629 6.549 14.629 14.629a14.631 14.631 0 01-14.629 14.629zm0-27.429C8.58 3.201 2.858 8.901 2.83 15.95S8.48 28.744 15.529 28.8c7.049.056 12.816-5.598 12.9-12.647A12.8 12.8 0 0015.629 3.2zm8.685 19.81l-9.448-6.552V7.01h1.524v8.686l8.686 6.095-.762 1.219z"
    />
  </svg>
))
export default SvgDurationTime
