/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgEdit = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M28 9.941L9.995 28 4 21.986 22.076 4 28 9.941zM7.541 30.216L1.337 31.96A1.052 1.052 0 01.04 30.663l1.744-6.204c.049-.173.141-.331.269-.459L8 29.947c-.127.127-.285.22-.459.269zm23.84-23.709L29.889 8 24 2.107 25.498.62a2.11 2.11 0 012.984-.005l2.911 2.913a2.117 2.117 0 01-.011 2.979z"
    />
  </svg>
))
export default SvgEdit
