/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgInformation = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M16 32C7.163 32 0 24.837 0 16S7.163 0 16 0s16 7.163 16 16-7.163 16-16 16zm2.704-23.52V5.184c0-.192-.037-.325-.112-.4s-.208-.112-.4-.112h-4.384c-.192 0-.325.037-.4.112s-.112.208-.112.4V8.48c0 .192.037.325.112.4s.208.112.4.112h4.384c.192 0 .325-.037.4-.112s.112-.208.112-.4zm-5.024 3.136v15.872c0 .192.037.325.112.4s.208.112.4.112h3.616c.192 0 .325-.037.4-.112s.112-.208.112-.4V11.616c0-.192-.037-.325-.112-.4s-.208-.112-.4-.112h-3.616c-.192 0-.325.037-.4.112s-.112.208-.112.4z"
    />
  </svg>
))
export default SvgInformation
