/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgLoadingSpinner = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      opacity={0.7}
      d="M16.727 0v6.1a9.452 9.452 0 015.527 2.4l4.17-4.3C23.764 1.678 20.335.193 16.727 0z"
    />
    <path
      fill="currentColor"
      opacity={0.1}
      d="M23.321 22.5l4.17 4.3c2.445-2.743 3.886-6.279 4.073-10h-6.012a10.07 10.07 0 01-2.23 5.7z"
    />
    <path
      fill="currentColor"
      opacity={0.6}
      d="M9.649 8.4A9.453 9.453 0 0115.273 6V0c-3.608.193-7.037 1.678-9.697 4.2l4.073 4.2z"
    />
    <path
      fill="currentColor"
      opacity={0.5}
      d="M8.582 9.5L4.509 5.2C2.064 7.943.623 11.479.436 15.2h5.915a10.07 10.07 0 012.23-5.7z"
    />
    <path
      fill="currentColor"
      opacity={0.2}
      d="M22.255 23.6a9.458 9.458 0 01-5.527 2.4v6c3.608-.193 7.037-1.678 9.697-4.2l-4.17-4.2z"
    />
    <path
      fill="currentColor"
      opacity={0.8}
      d="M23.321 9.5a10.056 10.056 0 012.327 5.7h5.818c-.187-3.721-1.628-7.257-4.073-10L23.32 9.5z"
    />
    <path
      fill="currentColor"
      opacity={0.4}
      d="M6.351 16.8H.436c.187 3.721 1.628 7.257 4.073 10l4.17-4.3a10.056 10.056 0 01-2.327-5.7z"
    />
    <path
      fill="currentColor"
      opacity={0.3}
      d="M15.176 25.9a9.452 9.452 0 01-5.527-2.4l-4.17 4.3c2.66 2.522 6.089 4.007 9.697 4.2v-6.1z"
    />
  </svg>
))
export default SvgLoadingSpinner
