/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgLockOpen = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      color="currentColor"
      d="M17.5 23.805v3.342c0 .859-.672 1.553-1.5 1.553s-1.5-.694-1.5-1.553v-3.342a3.112 3.112 0 01-1.5-2.676c0-1.715 1.344-3.106 3-3.106s3 1.392 3 3.106a3.116 3.116 0 01-1.5 2.676zm9-10.441h-.033v-2.493C26.467 4.876 21.755 0 15.967 0c-5.4 0-9.857 4.243-10.434 9.675h3.05c.561-3.712 3.643-6.569 7.384-6.569 4.134 0 7.5 3.483 7.5 7.765v2.493H5.5c-.825 0-1.5.7-1.5 1.553v15.53C4 31.301 4.675 32 5.5 32h21c.825 0 1.5-.699 1.5-1.553v-15.53c0-.853-.675-1.553-1.5-1.553z"
    />
  </svg>
))
export default SvgLockOpen
