/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgLock = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M23.5 13.364h-15v-2.493c0-4.282 3.364-7.765 7.5-7.765s7.5 3.483 7.5 7.765v2.493zm-6 10.441v3.342c0 .859-.672 1.553-1.5 1.553s-1.5-.694-1.5-1.553v-3.342a3.116 3.116 0 01-1.5-2.676c0-1.715 1.344-3.106 3-3.106s3 1.392 3 3.106a3.114 3.114 0 01-1.5 2.676zm9-12.934C26.5 4.876 21.788 0 16 0 10.21 0 5.5 4.877 5.5 10.871v2.493c-.825 0-1.5.699-1.5 1.553v15.53C4 31.301 4.675 32 5.5 32h21c.825 0 1.5-.699 1.5-1.553v-15.53c0-.854-.675-1.553-1.5-1.553v-2.493z"
    />
  </svg>
))
export default SvgLock
