/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgMail = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M3 8.118V25h26V8.118L18.377 17.95a3.5 3.5 0 01-4.755 0L2.999 8.118zM25.792 7H6.208l9.452 8.749a.5.5 0 00.679 0L25.791 7zM2 4h28a2 2 0 012 2v20a2 2 0 01-2 2H2a2 2 0 01-2-2V6a2 2 0 012-2z"
    />
  </svg>
))
export default SvgMail
