/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgMapNavigation = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M26.702 16.457l5.224 14.629H.074l5.225-14.629h4.836c.327.624.66 1.235.993 1.829h-4.54L2.669 29.257h26.662l-3.918-10.971h-4.476c.334-.593.666-1.205.993-1.829h4.772zM16.033.914c3.931 0 7.118 3.187 7.118 7.119s-7.118 14.824-7.118 14.824S8.915 11.963 8.915 8.033A7.118 7.118 0 0116.033.914zm0 9.617a2.996 2.996 0 100-5.993 2.996 2.996 0 000 5.993z"
    />
  </svg>
))
export default SvgMapNavigation
