/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgMore = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M3.81 19.619a3.81 3.81 0 110-7.62 3.81 3.81 0 010 7.62zm12.19 0a3.81 3.81 0 110-7.62 3.81 3.81 0 010 7.62zm12.19 0a3.81 3.81 0 110-7.62 3.81 3.81 0 010 7.62z"
    />
  </svg>
))
export default SvgMore
