/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgNext = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path fill="currentColor" d="M10.752 0L8 2.4 19.562 16 8 29.6l2.752 2.4 13.766-16z" />
  </svg>
))
export default SvgNext
