/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgNotificationAlert = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M15.972 28.585a4.896 4.896 0 01-4.752-3.731h9.503a4.895 4.895 0 01-4.752 3.731zm8.162-10.949a2.806 2.806 0 012.565 2.786 2.807 2.807 0 01-2.798 2.799H8.044a2.808 2.808 0 01-2.799-2.799 2.805 2.805 0 012.565-2.786V12.96a8.165 8.165 0 015.83-7.822v-.69c0-1.346 1.102-2.449 2.449-2.449s2.448 1.102 2.448 2.449v.764a8.163 8.163 0 015.597 7.748v4.676zm5.268-.374c0-2.106-.484-4.101-1.347-5.88h2.565c.729 1.82 1.134 3.803 1.134 5.88s-.405 4.06-1.134 5.88h-2.565a13.436 13.436 0 001.347-5.88zm-27.05 0c0 2.106.484 4.101 1.347 5.88H1.134C.405 21.322 0 19.339 0 17.262s.405-4.06 1.134-5.88h2.565a13.436 13.436 0 00-1.347 5.88z"
    />
  </svg>
))
export default SvgNotificationAlert
