/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgPin1 = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="inherit"
      opacity={0.7}
      d="M15.647 21.376c-4.644 0-8.409-3.791-8.409-8.468s3.765-8.468 8.409-8.468 8.409 3.791 8.409 8.468-3.765 8.468-8.409 8.468z"
    />
    <path
      fill="currentColor"
      d="M15.647 20.445c-4.231 0-7.662-3.454-7.662-7.715s3.43-7.715 7.662-7.715 7.662 3.454 7.662 7.715c0 4.261-3.43 7.715-7.662 7.715zm0-20.352c-7.041 0-12.77 5.768-12.77 12.858 0 4.308 3.705 9.879 5.298 12.075.519.716 5.141 6.991 7.471 6.991 3.262 0 12.77-12.255 12.77-19.066 0-7.09-5.728-12.858-12.77-12.858z"
    />
  </svg>
))
export default SvgPin1
