/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgPrint = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M6 2v8H0v16.667h4.667v4.667h22.667v-4.667h4.667V10h-7.333V2H6.001zm2.667 7.999V4.667h13.335v5.332H8.667zm-6 2.668h26.667V24h-2v-4.667H4.667V24h-2V12.667zm4.666 16.001V22h17.333v6.668H7.333z"
    />
  </svg>
))
export default SvgPrint
