/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgRefresh = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M26.537 21.526L32 16.063h-3.902a14.05 14.05 0 10-4.682 10.458l-2.029-2.341A10.925 10.925 0 014.058 11.663a10.927 10.927 0 0120.919 4.4h-3.902l5.463 5.463z"
    />
  </svg>
))
export default SvgRefresh
