/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgSearch = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M0 29.314zm14.173-11.721l.878.693A7.95 7.95 0 0020 20a8 8 0 10-8-8c0 1.713.535 3.334 1.516 4.688l.656.905zM3.757 30.243zm-1.414 1.414L0 29.314l10.278-10.278A11.948 11.948 0 018 12C8 5.373 13.373 0 20 0s12 5.373 12 12-5.373 12-12 12c-2.804 0-5.384-.962-7.427-2.573l-10.23 10.23z"
    />
  </svg>
))
export default SvgSearch
