/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgShown = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M15.977 13.574a2.755 2.755 0 100 5.51 2.755 2.755 0 000-5.51zm7.1 6.721c.658-1.174 1.034-2.527 1.034-3.966s-.376-2.793-1.035-3.967c2.538 1.313 4.53 2.991 5.578 3.966-1.048.975-3.04 2.654-5.577 3.966zm-14.195-7.94a8.09 8.09 0 00-1.04 3.975c0 1.439.376 2.792 1.034 3.966-2.539-1.313-4.532-2.992-5.579-3.967 1.047-.977 3.04-2.66 5.584-3.973zm7.095 9.733c-3.175 0-5.758-2.583-5.758-5.758s2.583-5.758 5.758-5.758 5.758 2.583 5.758 5.758a5.764 5.764 0 01-5.758 5.758zm15.247-6.559c-.277-.304-6.883-7.444-15.247-7.444S1.007 15.225.73 15.529L0 16.33l.73.801c.277.304 6.883 7.444 15.247 7.444s14.97-7.14 15.247-7.444l.73-.801-.73-.801z"
    />
  </svg>
))
export default SvgShown
