/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgSliderOff = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M9.6 26C4.298 26 0 21.523 0 16S4.298 6 9.6 6h12.8c5.302 0 9.6 4.477 9.6 10s-4.298 10-9.6 10H9.6z"
    />
    <path fill="inherit" d="M18.002 16a8 8 0 01-8 8 8 8 0 118-8z" />
  </svg>
))
export default SvgSliderOff
