/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgStatus = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M16.291 0v6.1a9.452 9.452 0 015.527 2.4l4.17-4.3C23.328 1.678 19.899.193 16.291 0zm6.594 22.5l4.17 4.3c2.445-2.743 3.886-6.279 4.073-10h-6.012a10.07 10.07 0 01-2.23 5.7zM9.212 8.4A9.453 9.453 0 0114.836 6V0c-3.608.193-7.037 1.678-9.697 4.2l4.073 4.2zM8.145 9.5L4.072 5.2C1.627 7.943.186 11.479-.001 15.2h5.915a10.07 10.07 0 012.23-5.7zM21.818 23.6a9.458 9.458 0 01-5.527 2.4v6c3.608-.193 7.037-1.678 9.697-4.2l-4.17-4.2zm1.067-14.1a10.056 10.056 0 012.327 5.7h5.818c-.187-3.721-1.628-7.257-4.073-10l-4.073 4.3zM5.915 16.8H0c.187 3.721 1.628 7.257 4.073 10l4.17-4.3a10.056 10.056 0 01-2.327-5.7zm8.824 9.1a9.452 9.452 0 01-5.527-2.4l-4.17 4.3c2.66 2.522 6.089 4.007 9.697 4.2v-6.1z"
    />
  </svg>
))
export default SvgStatus
