/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgSwap = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M20.026 9.289H6V6.643h14.043l-4.988-4.988L16.709.001l7.984 7.984-7.859 7.859-1.681-1.681 4.872-4.872zM10.65 22.611h14.043v2.646H10.667l4.872 4.872-1.681 1.681-7.859-7.859 7.984-7.984 1.654 1.654-4.988 4.988z"
    />
  </svg>
))
export default SvgSwap
