/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgYesTick = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 16 16" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M4.125 11.916L0 7.748l2.062-2.084 4.125 4.168L13.937 2 16 4.084 6.187 14l-2.062-2.084z"
    />
  </svg>
))
export default SvgYesTick
