/* eslint-disable deprecation/deprecation */

/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
/** @deprecated */

const SvgZoomFind = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="inherit"
      d="M13.268 7.445l-2.277.122c-.071-.936-.367-.845-.944-1.517l1.825-1.825c.93 1.022 1.446 1.468 1.597 2.73H17.6a11.27 11.27 0 01-2.935 7.087l-3.026-3.026a7.006 7.006 0 001.629-3.57zM7.143 2a6.804 6.804 0 014.279 1.77L9.597 5.595A4.229 4.229 0 007.144 4.58V2zM4.049 5.595L2.224 3.77A6.8 6.8 0 016.503 2v2.58A4.223 4.223 0 004.05 5.595zm-.454.454A4.229 4.229 0 002.58 8.502H0a6.804 6.804 0 011.77-4.279l1.825 1.825zm7.289 5.721l3.026 3.022a11.267 11.267 0 01-7.087 2.935v-4.271a7.01 7.01 0 004.061-1.687zM2.58 9.143a4.223 4.223 0 001.015 2.453L1.77 13.421A6.8 6.8 0 010 9.142h2.58zm3.923 3.919v2.58a6.804 6.804 0 01-4.279-1.77l1.825-1.825a4.229 4.229 0 002.453 1.015z"
    />
    <path
      fill="currentColor"
      d="M31.712 29.959l-9.288-9.288a10.141 10.141 0 10-15.787.566 10.141 10.141 0 0013.74 1.481l9.288 9.284 2.046-2.042zM9.193 19.73a7.233 7.233 0 1110.228 0 7.24 7.24 0 01-10.212 0h-.016z"
    />
  </svg>
))
export default SvgZoomFind
