/* eslint-disable no-unused-vars */
function templateFn({ template }, opts, { imports, componentName, props, jsx, exports }) {
  const code = `
  /* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
  import React, { forwardRef, SVGProps, Ref } from 'react';
  const COMPONENT_NAME = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => JSX);
  export default COMPONENT_NAME;
  `
  const tpl = template.smart(code, {
    plugins: ['typescript'],
    preserveComments: true,
  })

  return tpl({
    COMPONENT_NAME: componentName,
    JSX: jsx,
  })
}

module.exports = templateFn
