/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import * as Icons from './'
const all = [
  { name: 'Blog', component: Icons.Blog },
  { name: 'Facebook', component: Icons.Facebook },
  { name: 'Instagram', component: Icons.Instagram },
  { name: 'LinkedIn', component: Icons.LinkedIn },
  { name: 'MailShare', component: Icons.MailShare },
  { name: 'Twitter', component: Icons.Twitter },
  { name: 'Youtube', component: Icons.Youtube },
]
export default all
