/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgFacebook = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="#4460a0"
      d="M16.899 29.176H4.278a1.454 1.454 0 01-1.454-1.455V4.277c0-.803.651-1.454 1.454-1.454h23.444c.803 0 1.454.651 1.454 1.454v23.444c0 .803-.651 1.455-1.454 1.455h-6.715V18.971h3.425l.513-3.977h-3.938v-2.539c0-1.152.32-1.936 1.971-1.936l2.106-.001V6.961c-.364-.048-1.614-.157-3.069-.157-3.036 0-5.115 1.853-5.115 5.257v2.933h-3.434v3.977H16.9v10.205z"
    />
  </svg>
))
export default SvgFacebook
