/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgLinkedIn = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="#007ebb"
      d="M28.894 27.465h-5.762v-8.332c0-2.181-.901-3.67-2.883-3.67-1.516 0-2.359 1.005-2.751 1.973-.147.348-.124.832-.124 1.316v8.713h-5.708s.074-14.759 0-16.1h5.708v2.527c.337-1.105 2.161-2.682 5.072-2.682 3.611 0 6.449 2.316 6.449 7.303v8.952zM5.892 9.351h-.037c-1.839 0-3.032-1.231-3.032-2.791 0-1.59 1.228-2.795 3.104-2.795 1.875 0 3.027 1.202 3.064 2.791 0 1.56-1.189 2.795-3.099 2.795zm-2.411 2.014h5.081v16.1H3.481v-16.1z"
    />
  </svg>
))
export default SvgLinkedIn
