/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMailShare = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="#1b5786"
      d="M2.824 27.106h26.353a.94.94 0 00.941-.941V6.589a.94.94 0 00-.941-.941H2.824a.94.94 0 00-.941.941v19.576c0 .52.421.941.941.941zM27.859 9.035v14.871a.94.94 0 01-.941.941H5.083a.94.94 0 01-.941-.941V9.148l11.215 10.405a.942.942 0 001.284-.003L27.859 9.036zm-11.214 7.299a.941.941 0 01-1.29 0L6.4 7.906h19.2l-8.955 8.428z"
    />
  </svg>
))
export default SvgMailShare
