/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgTwitter = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="#1da1f2"
      d="M30.295 7.902c-1.057.476-2.179.79-3.33.932a5.863 5.863 0 002.531-3.241 11.692 11.692 0 01-3.685 1.421 5.817 5.817 0 00-9.945 5.327A16.56 16.56 0 013.879 6.214a5.816 5.816 0 001.776 7.769 5.816 5.816 0 01-2.619-.71v.089a5.816 5.816 0 004.662 5.683 5.875 5.875 0 01-1.554.222l-1.11-.089a5.815 5.815 0 005.461 4.04 11.72 11.72 0 01-7.236 2.486l-1.376-.089a16.51 16.51 0 008.923 2.619c10.744 0 16.604-8.879 16.604-16.604v-.755a11.857 11.857 0 002.886-2.974z"
    />
  </svg>
))
export default SvgTwitter
