/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgYoutube = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="#d0021b"
      d="M30.761 10.214s-.298-2.085-1.191-2.979-2.449-1.225-3.012-1.291C22.322 5.646 16 5.646 16 5.646s-6.321 0-10.558.298c-.596.066-1.886.066-3.012 1.291s-1.191 2.979-1.191 2.979a45.715 45.715 0 00-.298 4.865v2.284c.011 1.637.111 3.272.298 4.898 0 0 .298 2.085 1.191 2.979s2.648 1.158 3.31 1.291c2.416.232 10.227.298 10.227.298s6.321 0 10.558-.298c.596-.066 1.887-.066 3.012-1.291s1.191-2.979 1.191-2.979c.198-1.626.309-3.261.331-4.898v-2.284a45.454 45.454 0 00-.298-4.865zm-17.872 9.929V11.67l8.142 4.269-8.142 4.203z"
    />
  </svg>
))
export default SvgYoutube
