/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgFlagGb = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 40 32" ref={svgRef} {...props}>
    <path fill="#fff" d="M0 0h40v32H0z" />
    <path
      fill="#be1e2d"
      d="M18 0h4v12h18v8H22v12h-4V20H0v-8h18V0zM0 1.436V0l11.765 9.481H9.969L0 1.435zm28.235 8.045L40 0v1.436l-9.969 8.046h-1.796zm0 13.038h1.796L40 30.565v1.436L28.235 22.52zm-18.266 0h1.796L0 32v-1.436l9.969-8.046z"
    />
    <path
      fill="#002b45"
      d="M0 9.481V3.555l7.059 5.926H0zM3.529 0H16.47v9.481h-.36L3.529 0zm29.412 9.481L40 3.555v5.926h-7.059zM23.529 0H36.47L23.889 9.481h-.36V0zm9.412 22.519H40v5.926l-7.059-5.926zm-9.412 0h.36L36.47 32H23.529v-9.481zM0 22.519h7.059L0 28.445v-5.926zm16.111 0h.36V32H3.53l12.581-9.481z"
    />
    <path fill="#2d2926" opacity={0.15} d="M38 30H2V2h36v28zm2-30H0v32h40V0z" />
  </svg>
))
export default SvgFlagGb
