/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgFlagRo = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 40 32" ref={svgRef} {...props}>
    <path fill="#fcd21d" d="M0 32h40V0H0z" />
    <path fill="#be1e2d" d="M26.4 32H40V0H26.4z" />
    <path fill="#1b5786" d="M0 32h13.6V0H0z" />
    <path fill="#2d2926" opacity={0.15} d="M38 30H2V2h36v28zm2-30H0v32h40V0z" />
  </svg>
))
export default SvgFlagRo
