/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgFlagNo = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 40 32" ref={svgRef} {...props}>
    <path fill="#002b45" d="M0 0h40v32H0z" />
    <path fill="#fff" d="M0 16h12.8v16H0V16zm16 0h24v16H16V16zM0 0h12.8v12.8H0V0zm16 0h24v12.8H16V0z" />
    <path
      fill="#be1e2d"
      d="M0 17.6h11.2V32H0V17.6zm17.6 0H40V32H17.6V17.6zM0 0h11.2v11.2H0V0zm17.6 0H40v11.2H17.6V0z"
    />
    <path fill="#2d2926" opacity={0.15} d="M38 30H2V2h36v28zm2-30H0v32h40V0z" />
  </svg>
))
export default SvgFlagNo
