/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgFlagLv = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 40 32" ref={svgRef} {...props}>
    <path d="M0 0h40v32H0z" fill="#fff" />
    <path d="M0 19.06h40V32H0zM0 0h40v12.5H0z" fill="#be1e2d" />
    <path d="M38 2v28H2V2h36m2-2H0v32h40z" fill="#2d2926" opacity={0.15} />
  </svg>
))
export default SvgFlagLv
