/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgArchive = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12 4a8 8 0 11-7.748 10h2.09A6.002 6.002 0 0018 11.999 6 6 0 007.751 7.762l1.907 1.906a.2.2 0 01.059.141.2.2 0 01-.2.2H4.2a.2.2 0 01-.2-.2V4.492a.2.2 0 01.342-.141l1.996 1.997a7.976 7.976 0 015.663-2.349zm1 4v4l2.536 2.121-1.414 1.414-3.121-2.536v-5h2z"
    />
  </svg>
))
export default SvgArchive
