/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgArrowDown = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M18 13.522l-4.986 5.399V19h-.073l-.925 1-.906-1h-.091l.001-.099L6 13.367 7.439 12l3.581 3.867L11.019 4h1.995v11.872l3.488-3.751L18 13.522z"
    />
  </svg>
))
export default SvgArrowDown
