/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgArrowUp = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M6 10.42l4.986-5.43v-.08h.073l.776-.844a.2.2 0 01.283-.012l.013.013.759.843h.091l-.001.1L18 10.577l-1.439 1.375-3.581-3.891L12.981 20h-1.995V8.057L7.498 11.83 6 10.421z"
    />
  </svg>
))
export default SvgArrowUp
