/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgAttach = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M19.571 10.586l-8.132 8.132c-1.563 1.563-4.094 1.563-5.657 0s-1.563-4.094 0-5.657l8.839-8.839a2.501 2.501 0 013.536 3.536l-8.132 8.132c-.389.389-1.025.389-1.414 0s-.389-1.025 0-1.414l7.425-7.425-1.061-1.061-7.425 7.425a2.501 2.501 0 003.536 3.536l8.132-8.132c1.563-1.563 1.563-4.094 0-5.657s-4.094-1.563-5.657 0l-8.839 8.839c-2.15 2.15-2.15 5.629 0 7.778s5.629 2.15 7.778 0l8.132-8.132-1.061-1.061z"
    />
  </svg>
))
export default SvgAttach
