/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBarChart = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path fill="currentColor" d="M8 8v14H6a2 2 0 01-2-2V8h4zm6-6v20h-4V2h4zm6 12v6a2 2 0 01-2 2h-2v-8h4z" />
  </svg>
))
export default SvgBarChart
