/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBasket = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M20 10l-.91 9.099a1 1 0 01-.995.9H5.905a1 1 0 01-.995-.9L4 10h16zm-9 2h-1v6h1v-6zm3 0h-1v6h1v-6zm3 0h-1v6h1v-6zm-9 0H7v6h1v-6zm3-10h2v5h8v2H3V7h8V2z"
    />
  </svg>
))
export default SvgBasket
