/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBolt = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12 22c5.523 0 10-4.477 10-10S17.523 2 12 2 2 6.477 2 12s4.477 10 10 10zm.66-17c.11 0 .2.09.2.2v5.228h2.66c.017 0 .034.002.05.006l.047.019a.2.2 0 01.078.272l-4.46 8.028a.2.2 0 01-.375-.097v-5.228H8.2a.207.207 0 01-.05-.006l-.047-.019a.2.2 0 01-.078-.272l4.46-8.028A.2.2 0 0112.66 5z"
    />
  </svg>
))
export default SvgBolt
