/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBookingList = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M20 15v2H8v-2h12zM6 15v2H4v-2h2zm14-4v2H8v-2h12zM6 11v2H4v-2h2zm14-4v2H8V7h12zM6 7v2H4V7h2z"
    />
  </svg>
))
export default SvgBookingList
