/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBookmark = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M6.341 21.659a.2.2 0 01-.342-.141V2.201c0-.11.09-.2.2-.2h11.8v19.517a.2.2 0 01-.342.141L11.998 16l-5.659 5.659z"
    />
    <path
      fill="inherit"
      d="M12 10.981L9.539 12.71a.2.2 0 01-.307-.223l.883-2.875L7.71 7.805a.2.2 0 01.117-.36l3.007-.048.975-2.845a.2.2 0 01.378 0l.975 2.845 3.007.048a.2.2 0 01.117.36l-2.405 1.807.883 2.875a.2.2 0 01-.306.222l-2.461-1.729z"
    />
  </svg>
))
export default SvgBookmark
