/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBuAboutDfds = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="1em" height="1em" ref={svgRef} {...props}>
    <path
      d="M23.87 3.41H10a.54.54 0 00-.18 0 .49.49 0 00-.12.13L0 20.47v.12h14a.54.54 0 00.18 0 .49.49 0 00.12-.13L24 3.59V3.42zM16 14.42v.05h-.1l-3.16-1.83 1.82 3.17h-5l1.83-3.17-3.21 1.87h-.09V9.63h.09l3.17 1.83-1.83-3.25v-.05h4.88v.05l-1.82 3.17 3.16-1.83h.1z"
      fill="currentColor"
    />
  </svg>
))
export default SvgBuAboutDfds
