/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBuFreightShipping = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path fill="inherit" d="M10 8v5H2V8h8zm10 0v5h-9V8h9zM10 2v5H2V2h8z" />
    <path
      fill="currentColor"
      opacity={0.99}
      d="M22 14l-2.833 6.765a2 2 0 01-1.844 1.227L2 21.999v-8h20zm-4.762 2c-.526 0-.952.448-.952 1s.426 1 .952 1 .952-.448.952-1-.426-1-.952-1zm-2.857 0c-.526 0-.952.448-.952 1s.426 1 .952 1 .952-.448.952-1-.426-1-.952-1zm-2.857 0c-.526 0-.952.448-.952 1s.426 1 .952 1 .952-.448.952-1-.426-1-.952-1z"
    />
  </svg>
))
export default SvgBuFreightShipping
