/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBuPax = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12.498 10.083c2.906.306 7.547 2.917 7.547 4.935l-1.875 5.324c-.865.245-1.13 1.072-2.258 1.072-1.245 0-2.595-1.009-3.834-1.127l.419-10.204zm-8.794 4.935c0-2.018 4.642-4.629 7.547-4.935l.419 10.204c-1.239.118-2.59 1.127-3.835 1.127-1.128 0-1.392-.828-2.257-1.072l-1.875-5.324zm2.699-6.562h11.158l-.031-.058c-.543-1.016-.94-.995-3.862-.995h-3.372c-2.922 0-3.319-.021-3.862.995l-.031.058zm7.251-2.709H21l-.653 1.854h-1.589l1.144 5.994c-.856-1.029-2.323-2.456-3.858-3.235 1.846-.07 2.205-.317 1.865-1.181H6.054c-.329.834-.006 1.094 1.678 1.174-1.741.874-3.193 2.516-3.833 3.716l1.342-6.468H3.652l-.653-1.854h7.346L11.458 2h1.082l1.113 3.747z"
    />
  </svg>
))
export default SvgBuPax
