/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCalendar = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M17.5 2a1 1 0 011 1v2h.5a2 2 0 012 2v15.5H3V7a2 2 0 012-2h.5V3a1 1 0 012 0v2h9V3a1 1 0 011-1zm2 7h-15v12h15V9zm-8 8v2h-2v-2h2zm-3 0v2h-2v-2h2zm6 0v2h-2v-2h2zm3 0v2h-2v-2h2zm-6-3v2h-2v-2h2zm-3 0v2h-2v-2h2zm6 0v2h-2v-2h2zm3 0v2h-2v-2h2zm-3-3v2h-2v-2h2zm-3 0v2h-2v-2h2zm6 0v2h-2v-2h2zm-9 0v2h-2v-2h2z"
    />
  </svg>
))
export default SvgCalendar
