/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgChevronLeft = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path fill="currentColor" d="M15.754 7.207l-4.698 4.842 5.178 4.325-1.446 1.488-6.783-5.653 6.155-6.331z" />
  </svg>
))
export default SvgChevronLeft
