/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgClear = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12 4a8 8 0 110 16 8 8 0 010-16zm2.828 3.757L12 10.586 9.172 7.757 7.758 9.171l2.829 2.828-2.829 2.828 1.414 1.414L12 13.412l2.828 2.829 1.414-1.414-2.829-2.828 2.829-2.828-1.414-1.414z"
    />
  </svg>
))
export default SvgClear
