/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCopy = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M4 4h14a2 2 0 00-2-2H4a2 2 0 00-2 2v12a2 2 0 002 2V4zm2 16a2 2 0 002 2h12a2 2 0 002-2V8a2 2 0 00-2-2H8a2 2 0 00-2 2v12zm2 0V8h12v12H8z"
    />
  </svg>
))
export default SvgCopy
