/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgDelete = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M14.8 2.5c.11 0 .2.09.2.2V5h4.8c.11 0 .2.09.2.2v1.6a.2.2 0 01-.2.2h-.867l-.921 13.813a.2.2 0 01-.2.187H6.186a.2.2 0 01-.2-.187L5.065 7h-.867a.2.2 0 01-.2-.2V5.2c0-.11.09-.2.2-.2h4.8V2.7c0-.11.09-.2.2-.2h5.6zM9 8H8v11h1V8zm3.5 0h-1v11h1V8zM16 8h-1v11h1V8zm-2.5-4h-3v1h3V4z"
    />
  </svg>
))
export default SvgDelete
