/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgDocument = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M15 2l5 6v12c0 1-1 2-2 2H6c-1.105 0-2-1-2-2V4c0-1 .895-2 2-2h9zm1 14v2H8v-2h8zm0-3v2H8v-2h8zm0-3v2H8v-2h8zm-2-2V4H6v16h12V8h-4z"
    />
  </svg>
))
export default SvgDocument
