/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgDownload = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M11 14.947V15h.048l.822.903a.2.2 0 00.295.002l5.851-6.318-1.502-1.401L13 11.954V4h-2v7.914l-3.574-3.85-1.442 1.367L11 14.947zM6 18h12v2H6v-2z"
      fill="currentColor"
    />
  </svg>
))
export default SvgDownload
