/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgDuplicate = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M16 2a2 2 0 012 2H4v14a2 2 0 01-2-2V4a2 2 0 012-2h12zm-1 8v3h3v2h-3v3h-2v-3h-3v-2h3v-3h2zm5-4a2 2 0 012 2v12a2 2 0 01-2 2H8a2 2 0 01-2-2V8a2 2 0 012-2h12zm0 2H8v12h12V8z"
    />
  </svg>
))
export default SvgDuplicate
