/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgFiltersAdvanced = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M10 15v4H8v-1H3v-2h5v-1h2zm11 1v2H11v-2h10zm-3-6v1h3v2h-3v1h-2v-4h2zm-3 1v2H3v-2h12zM8 5v4H6V7.99H3V6h3V5h2zm13 1v2H9V6h12z"
    />
  </svg>
))
export default SvgFiltersAdvanced
