/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgInformation = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12.974 10.75c.103 0 .175.014.216.041s.06.077.06.148v5.871c0 .071-.02.12-.06.148s-.112.041-.216.041h-1.948c-.103 0-.175-.014-.216-.041s-.06-.077-.06-.148v-5.871c0-.071.02-.12.06-.148s.112-.041.216-.041h1.948zM13.013 7c.089 0 .15.022.185.065s.052.12.052.231v1.907c0 .111-.017.188-.052.231s-.096.065-.185.065h-2.027c-.089 0-.15-.022-.185-.065s-.052-.12-.052-.231V7.296c0-.111.017-.188.052-.231S10.897 7 10.986 7h2.027zM12 2c5.523 0 10 4.477 10 10s-4.477 10-10 10S2 17.523 2 12 6.477 2 12 2zm0 2a8 8 0 100 16 8 8 0 000-16z"
    />
  </svg>
))
export default SvgInformation
