/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgLink = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M7.05 11.293a2 2 0 012.828 0l-4.243 4.243 2.828 2.828 4.243-4.243a2 2 0 010 2.828l-2.828 2.828a2 2 0 01-2.828 0l-2.828-2.828a2 2 0 010-2.828l2.828-2.828zm7.071-7.071a2 2 0 012.828 0l2.828 2.828a2 2 0 010 2.828l-2.828 2.828a2 2 0 01-2.828 0l4.243-4.243-2.828-2.828-4.243 4.243a2 2 0 010-2.828l2.828-2.828zm.707 3.535l1.414 1.414-7.071 7.071-1.414-1.414 7.071-7.071z"
    />
  </svg>
))
export default SvgLink
