/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgLocationPin = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12 2a7 7 0 015.744 11.001L17.75 13l-5.581 8.736a.2.2 0 01-.337 0L6.251 13a6.996 6.996 0 01-1.25-4 7 7 0 017-7z"
    />
    <path fill="inherit" d="M15 9a3 3 0 11-6 0 3 3 0 016 0z" />
  </svg>
))
export default SvgLocationPin
