/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgLocked = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M15 2a3 3 0 013 3v4a2 2 0 012 2v9a2 2 0 01-2 2H6a2 2 0 01-2-2v-9a2 2 0 012-2V5a3 3 0 013-3zm-3 11a1.5 1.5 0 00-.869 2.723l.118.076V18h1.5l.001-2.202a1.5 1.5 0 00-.751-2.799zm3-9H9a1 1 0 00-1 1v4h8V5a1 1 0 00-1-1z"
    />
  </svg>
))
export default SvgLocked
