/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMail = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M3.101 6.372L12 14l8.9-7.627c.065.197.1.408.1.627v10a2 2 0 01-2 2H5a2 2 0 01-2-2V7c0-.219.035-.431.101-.628zM19 5c.521 0 .996.199 1.352.526L12 12.683 3.65 5.524C4.006 5.198 4.48 5 5 5h14z"
    />
  </svg>
))
export default SvgMail
