/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMoreVertical = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M14 5a2 2 0 11-3.999.001A2 2 0 0114 5zm0 7a2 2 0 11-3.999.001A2 2 0 0114 12zm0 7a2 2 0 11-3.999.001A2 2 0 0114 19z"
    />
  </svg>
))
export default SvgMoreVertical
