/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgMoreHorizontal = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M5 10a2 2 0 11.001 3.999A2 2 0 015 10zm7 0a2 2 0 11.001 3.999A2 2 0 0112 10zm7 0a2 2 0 11.001 3.999A2 2 0 0119 10z"
    />
  </svg>
))
export default SvgMoreHorizontal
