/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgNotification = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M14 19c0 1.177-.895 2.131-2 2.131-1.054 0-1.918-.87-1.995-1.972L10 19h4zm7-3v2H3v-2h18zM12.051 2.991a6.506 6.506 0 016.352 5.864l.596 6.027h-14l.661-6.248a6.307 6.307 0 016.391-5.643z"
    />
  </svg>
))
export default SvgNotification
