/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgPayment = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M4 6h16a2 2 0 012 2v1H2V8a2 2 0 012-2zm18 5v7a2 2 0 01-2 2H4a2 2 0 01-2-2v-7h20zm-2.75 3h-2.5a.75.75 0 000 1.5h2.5a.75.75 0 000-1.5zM14 14H4v1.5h10V14z"
    />
  </svg>
))
export default SvgPayment
