/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgPin = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M6.364 10.528a2 2 0 012.828 0l4.243 4.243a2 2 0 01.102 2.719l-.102.109-2.828-2.828-7.071 5.657 5.657-7.071-2.828-2.828zm14.849-.707a2 2 0 01-2.828 0l-4.243 4.243-4.243-4.243 4.243-4.243a2 2 0 010-2.828l7.071 7.071z"
    />
  </svg>
))
export default SvgPin
