/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgPlay = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" ref={svgRef} {...props}>
    <path
      d="M7.33 3.148l12.337 8.258c.368.246.442.711.167 1.04a.794.794 0 01-.167.148L7.331 20.852c-.368.245-.89.179-1.165-.149A.691.691 0 016 20.258V3.742c0-.41.372-.742.832-.742a.9.9 0 01.499.148z"
      fill="currentColor"
    />
  </svg>
))
export default SvgPlay
