/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgPrint = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M18 22H6v-5H2V8a2 2 0 012-2h2V5h12v1h2a2 2 0 012 2v9h-4v5zm-1.5-9h-9v7.5h9V13zM5 8a1 1 0 100 2 1 1 0 000-2zm10 7v1H9v-1h6zm0 2v1H9v-1h6zm3-15v4H6V2h12z"
    />
  </svg>
))
export default SvgPrint
