/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgRefresh = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12 4c2.212 0 4.215.898 5.663 2.349l1.996-1.997a.2.2 0 01.342.141V9.81a.2.2 0 01-.2.2h-5.317a.2.2 0 01-.2-.2c0-.053.021-.104.059-.141l1.907-1.906a6 6 0 101.409 6.238h2.09a8 8 0 11-7.748-10z"
    />
  </svg>
))
export default SvgRefresh
