/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgScroll = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M16.59 14L18 15.522 12 22l-6-6.478L7.41 14 12 18.945 16.59 14zM12 2l6 6.478L16.59 10 12 5.055 7.41 10 6 8.478 12 2z"
    />
  </svg>
))
export default SvgScroll
