/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgSearchHistory = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M9.414 3a6.414 6.414 0 015.18 10.198l6.407 6.408-1.395 1.395-6.408-6.407a6.417 6.417 0 01-10-3.593h2.067a4.442 4.442 0 008.588-1.586 4.44 4.44 0 00-8.04-2.599l1.845 1.845a.2.2 0 01-.141.342H2.2a.2.2 0 01-.2-.2V3.486c0-.11.09-.2.2-.2.053 0 .104.021.141.059L4.405 5.41a6.4 6.4 0 015.008-2.406z"
    />
  </svg>
))
export default SvgSearchHistory
