/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgSearch = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M9.414 3a6.414 6.414 0 015.18 10.198l6.407 6.408-1.395 1.395-6.408-6.407A6.414 6.414 0 119.414 3zm0 1.973a4.44 4.44 0 100 8.88 4.44 4.44 0 000-8.88z"
    />
  </svg>
))
export default SvgSearch
