/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgSettings = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M18.457 4.283l-1.399 4.014a5.9 5.9 0 01.537.98l4.011.74-.074 3.557-4.046.913a6.954 6.954 0 01-.578 1.001l1.233 3.96-3.043 1.843-2.647-3.104c-.37.043-.744.052-1.117.025l-2.776 3.219-2.969-1.714 1.399-4.014a5.94 5.94 0 01-.537-.98l-4.011-.74.074-3.557 4.046-.913a6.954 6.954 0 01.578-1.001l-1.233-3.96 3.043-1.843 2.646 3.104a5.957 5.957 0 011.117-.025l2.776-3.219 2.969 1.714zm-5.084 5.379c-1.23-.71-2.831-.239-3.577 1.053s-.353 2.914.877 3.624 2.831.239 3.577-1.053.353-2.914-.877-3.624z"
    />
  </svg>
))
export default SvgSettings
