/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgShare = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M14 18.94v-4.38c-5.56 0-9.22 1.7-12 5.44C3.12 14.66 6.22 9.34 14 8.26V4l8 7.46-8 7.48z"
    />
  </svg>
))
export default SvgShare
