/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgShieldSuccess = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M5 3h14v9.32a8 8 0 01-4.422 7.155L12 20.764l-2.578-1.289A8 8 0 015 12.32V3zm3.528 18.264L12 23l3.472-1.736A10 10 0 0021 12.32V1H3v11.32a10 10 0 005.528 8.944zm2.68-6.557l6-6-1.415-1.414-5.293 5.293-1.793-1.793-1.414 1.414 2.5 2.5.707.707.707-.707z"
      fill="currentColor"
    />
  </svg>
))
export default SvgShieldSuccess
