/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgShieldWarning = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M5 3h14v9.32a8 8 0 01-4.422 7.155L12 20.764l-2.578-1.289A8 8 0 015 12.32V3zm3.528 18.264L12 23l3.472-1.736A10 10 0 0021 12.32V1H3v11.32a10 10 0 005.528 8.944zM10.806 6.05c.038-.034.105-.051.202-.051h1.984c.097 0 .163.017.201.05.037.035.057.095.057.182l-.21 5.536c0 .087-.018.148-.057.181-.037.034-.104.051-.201.051h-1.565c-.096 0-.164-.018-.2-.05-.038-.034-.057-.095-.057-.182l-.21-5.536c0-.087.018-.147.056-.181zm2.388 9.639c-.039.04-.105.06-.202.06h-1.984c-.097 0-.164-.02-.201-.06-.038-.041-.057-.112-.057-.217v-1.947c0-.104.019-.175.056-.216.038-.04.105-.06.202-.06h1.984c.097 0 .163.02.201.06.038.04.057.112.057.216v1.947c0 .105-.019.176-.056.217z"
      fill="currentColor"
    />
  </svg>
))
export default SvgShieldWarning
