/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgShow = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12 5C9.067 5 5.4 7.333 1 12c4.4 4.667 8.067 7 11 7s6.6-2.333 11-7c-4.4-4.667-8.067-7-11-7zm0 2a5 5 0 11-.001 10.001A5 5 0 0112 7zm0 2a3 3 0 110 6 3 3 0 010-6z"
    />
  </svg>
))
export default SvgShow
