/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgStack = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      d="M4 8V5.11a.2.2 0 01.094-.169l7.8-4.875a.2.2 0 01.212 0l7.8 4.875a.2.2 0 01.094.17V8l-8 6-8-6z"
      fill="currentColor"
    />
    <path d="M4 13V9l8 6 8-6v4l-8 6-8-6z" fill="currentColor" />
    <path
      d="M4.08 18.06A.2.2 0 014 17.9V14l8 6 8-6v3.9a.2.2 0 01-.08.16l-7.8 5.85a.2.2 0 01-.24 0l-7.8-5.85z"
      fill="currentColor"
    />
  </svg>
))
export default SvgStack
