/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgStatusWarning = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M11.008 9.061c-.097 0-.164.018-.201.05-.039.035-.057.095-.057.182l.21 5.536c0 .088.018.148.056.182.037.033.105.05.201.05h1.565c.097 0 .164-.017.201-.05.038-.034.057-.094.057-.182l.21-5.536c0-.087-.02-.147-.056-.181-.039-.033-.105-.05-.202-.05h-1.984zm1.984 9.75c.097 0 .163-.02.202-.06.037-.041.056-.112.056-.216v-1.948c0-.103-.019-.175-.056-.216-.039-.039-.105-.06-.202-.06h-1.984c-.097 0-.164.021-.201.06-.038.04-.057.113-.057.216v1.948c0 .104.019.175.056.216.038.04.105.06.202.06h1.984zm-.89-16.782a.2.2 0 01.07.068l11.646 19.411a.2.2 0 01-.171.303H.353a.2.2 0 01-.171-.303l11.646-19.41a.2.2 0 01.275-.07zM12 5.699L3.532 19.81h16.935L12 5.698z"
    />
  </svg>
))
export default SvgStatusWarning
