/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgSwapHorziontal = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M6 7.2c0-.11.09-.2.2-.2h9.84l-1.823-1.59L15.618 4 20 8l-4.382 4-1.401-1.41L16.042 9H6.2a.2.2 0 01-.2-.2V7.2zM4 16l4.382-4 1.401 1.41-1.826 1.591L18.8 15c.11 0 .2.09.2.2v1.6a.2.2 0 01-.2.2l-10.841.001 1.824 1.589L8.382 20 4 16z"
    />
  </svg>
))
export default SvgSwapHorziontal
