/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgSwapVertical = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M16.8 6c.11 0 .2.09.2.2v9.84l1.59-1.823L20 15.618 16 20l-4-4.382 1.41-1.401L15 16.042V6.2c0-.11.09-.2.2-.2h1.6zM8 4l4 4.382-1.41 1.401-1.591-1.826L9 18.8a.2.2 0 01-.2.2H7.2a.2.2 0 01-.2-.2L6.999 7.959 5.41 9.783 4 8.382 8 4z"
    />
  </svg>
))
export default SvgSwapVertical
