/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgUnlink = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M11.908 14.736l1.066 1.065a1.99 1.99 0 01-.581 1.279l-2.828 2.828a2 2 0 01-2.828 0L3.909 17.08a2 2 0 010-2.828l2.828-2.828a1.99 1.99 0 011.279-.581l1.065 1.066-3.758 3.758 2.828 2.828 3.758-3.759zM3.515 3.515l1.414-1.414 5.65 5.65c.096-.207.229-.4.4-.57l2.828-2.828a2 2 0 012.828 0l2.828 2.828a2 2 0 010 2.828l-2.828 2.828c-.17.17-.364.304-.57.4l5.835 5.834-1.414 1.414L3.515 3.514zm6.272 9.1l1.414 1.414-2.343 2.344-1.414-1.414 2.344-2.344zm5.434-6.849l-3.313 3.313.707.707 1.899-1.899 1.414 1.414-1.9 1.899.707.707 3.314-3.313-2.828-2.828z"
    />
  </svg>
))
export default SvgUnlink
