/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgUnlocked = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M18 9a2 2 0 012 2v9a2 2 0 01-2 2H6a2 2 0 01-2-2v-9a2 2 0 012-2V5a3 3 0 013-3h6a3 3 0 013 3h-2l-.007-.117A1 1 0 0015 4H9a1 1 0 00-1 1v4h10zm-6 4a1.5 1.5 0 00-.75 2.799V18h1.5l.001-2.202A1.5 1.5 0 0012 12.999z"
    />
  </svg>
))
export default SvgUnlocked
