/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgUnpin = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M4.929 2.101l6.345 6.345 2.868-2.867a2 2 0 010-2.828l7.071 7.071a2 2 0 01-2.828 0l-2.868 2.867 6.383 6.383-1.414 1.414L3.515 3.515l1.414-1.414zm4.263 11.256l1.414 1.414-7.071 5.657 5.657-7.071zM7.2 10.027l6.736 6.736a1.973 1.973 0 01-.384.709l-.117.127-7.071-7.071a1.99 1.99 0 01.836-.501z"
    />
  </svg>
))
export default SvgUnpin
