/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgUpdate = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M12 4a8 8 0 107.748 10h-2.09A6.002 6.002 0 016 11.999a6 6 0 0110.249-4.237l-1.907 1.906a.197.197 0 00-.059.141c0 .11.09.2.2.2H19.8a.2.2 0 00.2-.2V4.492a.2.2 0 00-.342-.141l-1.996 1.997a7.976 7.976 0 00-5.663-2.349zm-1 4v5h.001l3.12 2.536 1.414-1.414-2.536-2.121v-4h-2z"
    />
  </svg>
))
export default SvgUpdate
