/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgUpload = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    width="1em"
    height="1em"
    viewBox="0 0 24 24"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
    ref={svgRef}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M18 20H6v-2h12v2zM13 5.022V5h-.02l-.85-.935a.2.2 0 00-.295-.001l-5.851 6.318 1.502 1.4L11 8.015V16h2V8.054l3.574 3.85 1.442-1.367L13 5.022z"
      fill="currentColor"
    />
  </svg>
))
export default SvgUpload
