/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgZoomOut = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    width="1em"
    height="1em"
    viewBox="0 0 32 32"
    fill="none"
    ref={svgRef}
    {...props}
  >
    <path
      fillRule="evenodd"
      clipRule="evenodd"
      d="M12.551 21.103c1.887 0 3.631-.611 5.045-1.646L26.14 28 28 26.14l-8.543-8.544a8.551 8.551 0 10-6.906 3.507zm0-2.631a5.92 5.92 0 110-11.84 5.92 5.92 0 010 11.84zM16 14v-2.667H9.333V14H16z"
      fill="currentColor"
    />
  </svg>
))
export default SvgZoomOut
