/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBaggageRestrictions = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M8.749 12.217v-2.69h7.45v2.69h-7.45zm12.248 0h-1.545V8.984a2.714 2.714 0 00-2.711-2.71H8.207a2.714 2.714 0 00-2.711 2.71v3.233H1.083C.488 12.217 0 12.705 0 13.3v11.987c0 .595.488 1.083 1.083 1.083h22.685c.597 0 1.085-.488 1.085-1.083v-9.241a6.58 6.58 0 01-3.856-3.83z"
    />
    <path
      fill="inherit"
      d="M29.608 8.225l-2.235 4.249a.576.576 0 01-.877.176l-2.379-1.963a.576.576 0 01.733-.889l1.833 1.513 1.905-3.622a.575.575 0 111.019.536zM27.1 5a4.9 4.9 0 000 9.8 4.9 4.9 0 000-9.8z"
    />
  </svg>
))
export default SvgBaggageRestrictions
