/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBasket = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg width="1em" height="1em" viewBox="0 0 24 18" xmlns="http://www.w3.org/2000/svg" ref={svgRef} {...props}>
    <g fillRule="nonzero" fill="#68B2E3" stroke="none" strokeWidth={1}>
      <path d="M22.08 8.514l-2.76 9.06a.578.578 0 01-.54.426H5.22c-.3 0-.54-.243-.6-.486l-2.76-9H.6c-.36 0-.6-.305-.6-.67V4.927c0-.365.3-.608.6-.608h5.58L8.46.304c.42-.669 1.44-.06 1.02.608L7.56 4.318h8.88L14.46.912c-.42-.669.66-1.277 1.02-.608l2.34 4.014h5.58c.3 0 .6.304.6.608v2.98c0 .303-.3.608-.66.608h-1.26zm-18.96 0l2.52 8.27H18.3l2.52-8.27H3.12zm19.68-2.98H1.2v1.763h21.6V5.534z" />
      <path d="M11.4 11.007c0-.852 1.2-.852 1.2 0v3.284c0 .79-1.2.79-1.2 0v-3.284zM7.08 11.128c-.12-.79 1.08-1.033 1.2-.243l.54 3.284c.18.79-1.02.973-1.14.182l-.6-3.223zM15.72 10.885c.12-.79 1.26-.547 1.14.243l-.54 3.223c-.12.79-1.32.608-1.2-.182l.6-3.284z" />
    </g>
  </svg>
))
export default SvgBasket
