/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgBed = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M30.861 14.531c.626 0 1.139.522 1.139 1.161v7.787c0 .639-.513 1.161-1.139 1.161h-1.477c.036.118.061.24.061.37v.539c0 .692-.551 1.254-1.23 1.254h-.529c-.679 0-1.23-.562-1.23-1.254v-.539c0-.13.025-.252.061-.37H5.822c.036.118.061.24.061.37v.539c0 .692-.551 1.254-1.23 1.254h-.529c-.68 0-1.23-.562-1.23-1.254v-.539c0-.13.025-.252.061-.37H1.141a1.153 1.153 0 01-1.139-1.161v-7.787c0-.639.513-1.161 1.139-1.161h1.712v-.003l28.01.003zM4.316 12.728l.001.029H2.851v-.972c0-3.182 2.555-5.786 5.677-5.786H23.84c3.123 0 5.677 2.604 5.677 5.786v.972h-1.452l.002-.029c0-1.237-.993-2.249-2.207-2.249h-7.521c-1.043 0-1.921.748-2.148 1.743-.227-.995-1.105-1.743-2.148-1.743H6.522c-1.214 0-2.207 1.012-2.207 2.249z"
    />
  </svg>
))
export default SvgBed
