/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgCaravan = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M31.17 18.96H29a.79.79 0 00-.07-.54l-2-4.42c-2.54-5.75-3.5-10-9-10H4a3 3 0 00-3 2.96v12a1.922 1.922 0 001.93 1.93h7.37v-.39a3.55 3.55 0 017.09 0v.39h13.78v-1.93zm-18-7.58a1 1 0 01-1 1h-8a1 1 0 01-1-1v-4a1 1 0 011-1h8a1 1 0 011 1v4zm7.84 0a1 1 0 01-1 1H16a1 1 0 01-1-1v-4a1 1 0 011-1h4a1 1 0 011 1l.01 4zm-7.21 6.58a2.488 2.488 0 012.51 2.5 2.5 2.5 0 11-2.51-2.5zm0 3.8a1.299 1.299 0 001.31-1.3 1.3 1.3 0 10-1.31 1.3z"
    />
  </svg>
))
export default SvgCaravan
