/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgDisability2 = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M22.394 16.638c.057-.005.116-.007.174-.007 1.175 0 2.13.971 2.13 2.164V31.62h-1.379V18.795c0-.421-.337-.763-.751-.763s-.751.342-.751.763h-1.379c0-.657.29-1.247.747-1.644a1.59 1.59 0 01-1.057-.424l-.326-.33-2.092-2.123-2.496 16.971c-.034.25-.102.374-.353.374l-.957.002c-.076 0-.239 0-.302-.099l-.399-.696-.438.716c-.032.046-.119.08-.197.08h-.855a.497.497 0 01-.509-.413L9.699 20.456l-1.254-.5a1.123 1.123 0 01-.628-1l.502-7.878a3.384 3.384 0 013.39-3.125h3.205c.743 0 1.223.192 1.525.492l5.918 6.012c.239.242.369.3.441.921.054.463-.13.949-.401 1.26zM13.219 6.375a2.958 2.958 0 110-5.917 2.958 2.958 0 010 5.917z"
    />
  </svg>
))
export default SvgDisability2
