/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgPushchair = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M23.786 11.949l2.856-2.856a3.178 3.178 0 001.591 1.591L25.4 13.518v4.539c0 .451-.37.82-.822.82H4.88a.823.823 0 01-.822-.82v-5.978l19.728-.131zm-5.995 14.02a2.496 2.496 0 104.993.001 2.496 2.496 0 00-4.993-.001zm-2.3 0a4.797 4.797 0 119.594 0 4.797 4.797 0 01-9.594 0zm-9.191 0a2.496 2.496 0 104.993.001A2.496 2.496 0 006.3 25.97zm-2.3 0a4.797 4.797 0 119.594 0 4.797 4.797 0 01-9.594 0zm.057-15.299C4.057 4.777 8.834 0 14.727 0v10.67H4.057z"
    />
  </svg>
))
export default SvgPushchair
