/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */
import React, { forwardRef, SVGProps, Ref } from 'react'
const SvgSaveMoney = forwardRef((props: SVGProps<SVGSVGElement>, svgRef: Ref<SVGSVGElement>) => (
  <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 32 32" ref={svgRef} {...props}>
    <path
      fill="currentColor"
      d="M31.406 19.937c-.847 3.363-2.292 6.463-5.141 7.519-7.441 2.753-15.463-2.542-21.079.742L0 23.012c2.783-1.179 6.324-5.705 10.445-6.232 2.137-.277 4.833.932 7.514 1.183 2.351.221 6.34-1.029 6.723 1.585.328 2.26-3.659 2.136-6.329 2.372 2.085.416 4.341 2.368 6.057 1.892 2.215-.61 3.368-3.885 4.911-4.834 1.748-1.076 2.418-.384 2.086.958z"
    />
    <path
      fill="inherit"
      d="M22.795 6.855c2.55 0 4.625 2.075 4.625 4.625s-2.075 4.626-4.625 4.626a4.632 4.632 0 01-4.449-3.375 4.61 4.61 0 01-.177-1.251 4.629 4.629 0 013.907-4.563c.235-.037.474-.062.719-.062zm-1.149-.968a5.719 5.719 0 00-4.561 5.594c0 .445.056.876.154 1.292a4.629 4.629 0 01-4.236-4.606 4.631 4.631 0 014.626-4.625c1.721 0 3.222.946 4.018 2.345z"
    />
  </svg>
))
export default SvgSaveMoney
